### ISSUE TITLE
Thankyou, f-droid and Dark Theme?

### ISSUE THREAD

**Issue by thanksnain** [Nain57/Smart-AutoClicker#1]
This app has saved me and many others hours of time, thanks for creating it.

2 requests,
Dark theme?
Do you give permission for this to be submitted to the f-droid appstore (a repository for open source android apps)

**Comment by Nain57** [comment]
Hi ! I'm glad to hear that it has been useful to someone else :)

For your requests:
- Dark mode will definitely be in the next release, but i'm a bit busy in my life right now so it will wait a bit
- I have already submitted it to F-Droid, i'm waiting for the merge request to be accepted (https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8865)

**Comment by madflower** [comment]
I installed it with fdroid but it installed rc4 instead of the current release.

**Comment by Nain57** [comment]
F-Droid can be really slow to detect update.
It's all automatic once I have published the released on GitHub, but it can take up to 2 weeks to be released on that store.

**Comment by Nain57** [comment]
Dark theme and even Material Dynamic colors have been implemented and will part of the next version.

**Comment by Nain57** [comment]
Release 2.0.0 containing a fix for this is now available on Github and should be available soon on F-Droid.

**Comment by Ero-gamer** [comment]
@Nain57 can you add manual option to select Dark theme in app settings? I'm using ColorOs 6.1 (A9) with no native dark theme support so the only option to use dark theme in app is to enable it in app settings. Should I create a new issue on this?
