### ISSUE TITLE
(feature request) Option To Simplify Use?

### ISSUE THREAD

**Issue by puppykickr** [Nain57/Smart-AutoClicker#103]
If the app is only used for a simple thing, it seems difficult to set it up to work properly.

This app works great for the above situation, but it is not FOSS as far as I am aware:
https://automatic-tap-auto-clicker-tap-sequence-recorder.en.uptodown.com/android

Could something similar be incorporated into your app?

**Comment by Nain57** [comment]
Conditionless click will not be implemented, as it goes against the core principle of the app.
