### ISSUE TITLE
Printing the position of the Condition.

### ISSUE THREAD

**Issue by BishoPower** [Nain57/Smart-AutoClicker#107]
I am looking to print the position of a Condition on the screen when you select detect "Anywhere on screen". Can you help me with this?

**Comment by Nain57** [comment]
Hi !
I have updated my code this morning to add the click on detection condition, and I think it might be easier to get this information now. The native detection now return the center position of the detected condition. It can be found [here](https://github.com/Nain57/Smart-AutoClicker/blob/master/detection/src/main/java/com/buzbuz/smartautoclicker/detection/ImageDetector.kt#L67).

Hope this helps !
