### ISSUE TITLE
Anywway to install update without uninstall old version

### ISSUE THREAD

**Issue by 19ChuAnh13** [Nain57/Smart-AutoClicker#112]
i have so many scenario so i dont want to uninstall old version to update app, how can i just override install new version?

**Comment by Nain57** [comment]
If you have an older version of the application, installing the new version will not erase your old data, as long as your install it from the same source.
You scenarios will be updated from the old format to the new format automatically, and nothing should change at the execution.

**Comment by 19ChuAnh13** [comment]
> If you have an older version of the application, installing the new version will not erase your old data, as long as your install it from the same source. You scenarios will be updated from the old format to the new format automatically, and nothing should change at the execution.

when i install it say "App not Installed". But when i install on a rooted phone with removed signature checking, no error appeared. I think there are some issues with the signature. And yes, i download from the same source

**Comment by Nain57** [comment]
That's weird. All my release build are signed with the same key stored on github, so your issue might be with F-Droid ? have you tried updating with their application ?

What version do you currently have ?

**Comment by 19ChuAnh13** [comment]
> That's weird. All my release build are signed with the same key stored on github, so your issue might be with F-Droid ? have you tried updating with their application ?
> 
> What version do you currently have ?

i have version 1.2.2, my device is Galaxy Note 10+ android 12, Sony XZ2 android 11. Both install from Github, not F-Droid

**Comment by 19ChuAnh13** [comment]
Solved, use F-Droid to update
