### ISSUE TITLE
What are the features of Visble/invisible?

### ISSUE THREAD

**Issue by hamoumiKen** [Nain57/Smart-AutoClicker#114]
What is the function of the new Visble/invisible toggle added in version 1.3.1?

**Comment by Nain57** [comment]
This new feature is the negation of the condition:
* If visible, the condition must be detected on the screen to trigger the actions
* If not visible, the condition must NOT be detected on the screen to trigger the actions

**Comment by hamoumiKen** [comment]
Thank you for your reply.
The specifications have changed quite a bit in this version, so if you could explain the new features, that would be very helpful and appreciated.
However, the feel of this version is a little different from the previous version, and there are some problems, such as not detecting images when switching from "at positon" to "Anywere on screen". This problem was solved by taking a new screenshot of the same image from the display, but I do not know the cause. I would like to degrade to the previous version and use it for a while, so if there is a way to degrade without leaving any data such as images or conditions, I want to know how to do so.

**Comment by Nain57** [comment]
Hi,
This is not possible to return to a previous version and keep your data.

Version 1.4.0 should be released soon and provide more tuning to the detection to help you.

**Comment by hamoumiKen** [comment]
That's wonderful.
Thanks for all your hard work, it's a great tool and I'm sure it will be a great addition to the site.
I will use it as soon as I can since I see it has already been released.

**Comment by laiqun** [comment]
I think we can change visible , not visible to Detected ,Not Detected.
It's Action, not status.
Action to detect status.
