### ISSUE TITLE
Issues with similar events

### ISSUE THREAD

**Issue by Tequeromtv** [Nain57/Smart-AutoClicker#123]
I played today a game where u need to swipe in directions, so I started to automate this bc I have other things to do, occours that it start using colors instead of directions, so theres green that could be on the top, bottom left or right, I tried to do this selecting the middle word Green and the correct path like 'top' (theres a diference between the wrong and right) but when I put the event green "bottom" the top stop working or both

I guess we can handle that by putting 2 conditions line instead of one, so in the first one we can put the principal one that is "green" and the variantes bellow, maybe with that we can make some actions for each variant, it makes the clicker more complex and with a lot of combintions usage

**Comment by Nain57** [comment]
Hi.
Your use case might need to tune a bit the algorithm quality (available with 1.4.0). Using this plus the debugger, you might be able to get high precision detection.
