### ISSUE TITLE
New version is crashing all time

### ISSUE THREAD

**Issue by me414e** [Nain57/Smart-AutoClicker#124]
Is there a way to downgrade without losing the scenarios I made?  My last version was 1.2.1 I think. I upgraded because the "executions before scenario end" function wasn't saving any number. But the new version, 1.3.1 just crash after some seconds with my old scenarios.
A way to backup de scenarios you have made would be nice in the future if someone needs to use them on a new phone.
Edit.: I did restart the phone and it is working now. But a backup would still be nice to people who are having trouble and think it is easier to delete the app and use an older apk just to put a stable version

**Comment by Nain57** [comment]
Hi.

I order to fix the issue, I need more information:
* Brand, Model and Android version of your phone.
* Details of the crash (when does it occur, in which situation ?)
* If possible, the logcat trace of the crash.

Thanks for your support

**Comment by me414e** [comment]
Hello,
1-Asus, ROG PHONE 2, Android 10
2-The crash occurs when I pause the application(annoyed me because I was trying to figure out what to edit on scenario to make it running perfectly like in the past) 
But the biggest issue is that my old 38-event doesn't work like intended anymore. 
I don't know what could be really happening, did the application got "heavier" to process the commands and that's why issues happen ?
I don't know how to post a logcat(I don't know what it) 
*I love your app, I use it daily since october
