### ISSUE TITLE
Can't make my condition work

### ISSUE THREAD

**Issue by Tsyoee** [Nain57/Smart-AutoClicker#126]
I entered a pink color capture and it will auto-click when the color appears, however, it auto-clicks before the pink target appears.,, please fix it sir,, i'm using bluestack 5.7.100.1036 N32 please make menu same with 1.2.4 version but suport for bluestack

**Comment by pseudomasq** [comment]
I have a similar problem in BS Pie Beta. I have the precision all the way to 1200. The target image is dimmer but it still triggers at 100%.

![image](https://user-images.githubusercontent.com/76476344/168091264-3c4dad04-5f47-4529-ad0b-dc720feb7a86.png)
![image](https://user-images.githubusercontent.com/76476344/168091307-a633c2b0-220a-405a-b33f-a01e8afdaf80.png)
