### ISSUE TITLE
How to swipe random for some point in your app?

### ISSUE THREAD

**Issue by NghiaK** [Nain57/Smart-AutoClicker#13]

**Comment by NghiaK** [comment]
how can i do that?

**Comment by NguyenDuck** [comment]
Please be more specific about your intentions!

**Comment by NghiaK** [comment]
Ví dụ em muốn nhập vào 1 tập điểm, xong chạy random swipe 2 điểm trong n điểm trong tập điểm đấy, và lập lại m lần. Mà em tải về edit rồi build thử toàn lỗi nhỉ. Em không rành github. :(
For example, I want to enter a set of points, then run random swipe 2 points in n points in that set of points, and repeat m times. But I download edit and try to build all errors. I'm not familiar with github. :(

**Comment by Nain57** [comment]
If I understand correctly, you want to execute a series of clicks/swipes with just a timer separating it, no image conditions required.

If that's the case, this functionality isn't supported by this application, as it is made to execute actions on a specific screen content.

**Comment by NghiaK** [comment]
I have list: (X1, X2, ... ,Xn) and (Y1, Y2, ..., Yn)
Random X1 = list (X1, X2, ... , Xn)
Random X2 = list (X1, X2, ... , Xn)
Random Y1 = list (Y1, Y2, ... , Yn)
Random Y2 = list (Y1, Y2, ... , Yn)
I want swipe P1 (X1, Y1) to P2 (X2, Y2)
How to add it into this app? Thanks!

**Comment by Nain57** [comment]
So if I understand correctly, you want to randomize the swipe for a list of possible positions ?
If that's the case, this is not supported and will probably not by Smart AutoClicker. But feel free to fork the project !

**Comment by NghiaK** [comment]
How to edit this app. I downloaded it by zip but I don't edit it.
![screenshot_1624530796](https://user-images.githubusercontent.com/86037444/123248623-54934f80-d512-11eb-818c-92a69d2cfcc1.png)

**Comment by Nain57** [comment]
This seems like an Android SDK issue. Your licenses haven't been accepted, which can happen if you have installed it without using the Android Studio embedded SDK manager.

This issue can come from a lot of things so I think you might want to check this issue on Google

**Comment by NghiaK** [comment]
Have a nice day!
Thank you very much!
