### ISSUE TITLE
Phone gets incredibly hot during usage.

### ISSUE THREAD

**Issue by jmschrack** [Nain57/Smart-AutoClicker#14]
I've used other auto-clickers before, but I love the smart nature of this one.

Unfortunately, I can't run it for long periods of time without the phone getting extremely hot.  I assume this is something to do with the ScreenDetection method of casting to a virtual screen.  

Would it be feasible to pause the virtual casting for a time after certain conditions?  For example, if a certain condition is met, tap a spot on screen, and then disable casting for 5min.  (Obviously, this would stop all events globally until casting is re-enabled since the screen is no longer being cast.)

**Comment by Nain57** [comment]
Thanks for your feedback.
I have noticed this phone temperature issue when using the application with some games. I will try to optimize the algorithm a bit more, and if I can't get satifisying results, I will try to find a solution.

For the casting pause, Android forbid any automatic clicks on the mandatory screen casting warning dialog, so it will not be possible to automatize it.
