### ISSUE TITLE
Frequent Crashes when pausing the clicker

### ISSUE THREAD

**Issue by Metazolid** [Nain57/Smart-AutoClicker#141]
Since 1.5.0, about 90% of the time I pause the Autoclicker, after about a second the menu disappears (the notification bar is still there as if the scenario is still active) and if it happens more often within a short period of time, the System will alert me that the app keeps crashing. In this case, the notification bar still shows the scenario as active though.

It might just be my imagination, but starting the scenario and then rapidly pausing and then starting it will prolong it for a while, so you can go on pausing it a few more times before it ultimatively "crashes" again.

Not sure how else to describe it, continuing after pause to basically "overwrite" the crash will mostly lead to the system popup about the crash but not anything else.

Running Android 10 on a Samsung Galaxy A9

**Comment by norrir** [comment]
Same issue here on moto g power 2020 w/ android 10

**Comment by Metazolid** [comment]
> the app's permission gets "revoked."
Same, but that also happened in the previous versions caused by unrelated crashes, so I assume this bug isn't linked specifically to 1.5.0/1.5.1.

**Comment by me414e** [comment]
Here too. Versions from 1.2.1 era didn't crashed when pausing.

**Comment by Nain57** [comment]
Is this issue still reproduced with the version 1.5.2 ?
Stability improvements have been made on this version.

**Comment by me414e** [comment]
No, it isnt. Thanks!

Em qui., 8 de set. de 2022 08:12, Nain57 ***@***.***>
escreveu:

**Comment by Nain57** [comment]
New version 1.5.3 include a potential fix for this issue.
It is available [here ](https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.5.3) and on F-Droid soon.

Let me know if you still encounter this problem
