### ISSUE TITLE
Feature suggestion - Search for actions applied in a scenario and Log

### ISSUE THREAD

**Issue by Metazolid** [Nain57/Smart-AutoClicker#142]
I think it would be very helpful to have the option to search for names that I have given to actions within an active scenario.
Right now for example I seem to have an "Enter" action that is firing when it's not supposed to and without knowing which action was responsible. I can only guess based on how the game responded to the action, an optional performance overlay like Steam Link provides could be very helpful, that can show the specific event that is currently in action.

**Comment by Nain57** [comment]
Debug mode & Debug report can now provide more information about what is executed and how many times.
Next version will integrate them definitely to the UI.
