### ISSUE TITLE
Creating a scenario backup crashes the application

### ISSUE THREAD

**Issue by Alexfield17** [Nain57/Smart-AutoClicker#146]
When I try to backup a scenario the application asks to select scenarios, then asks for a name for the backup file and crashes after clicking on the backup icon. A blank zip file is created.
Hardware: Samsung Galaxy A70
Android: 11
App version: 1.5.0

**Comment by Nain57** [comment]
Hi !
This issue has been fixed on Smart AutoClicker 1.5.1.
