### ISSUE TITLE
[Feature Request] Tutorial

### ISSUE THREAD

**Issue by fohfuu** [Nain57/Smart-AutoClicker#149]
Since the app is doing something that other apps haven't tried, it can be difficult to understand how it works. It would improve the experience immensely if there was an included tutorial that walked through each step of the process.

**Comment by Nain57** [comment]
Ui will be reworked completely to integrate explanations and hints for missing values.
Stay tuned for the next version

**Comment by Nain57** [comment]
Release 2.0.0 containing a fix for this is now available on Github and should be available soon on F-Droid.

**Comment by fohfuu** [comment]
I don't understand the process entirely but the hints are somewhat helpful.

I do not use gesture controls. Can I add a "back" action? I can't think of how any of the options in the actions menu would accomplish that.

I don't know if it's possible in this app at this time, this is just a question and not a feature request. That would be a different issue ofc.
