### ISSUE TITLE
[FR] Freeze screen image on condition select

### ISSUE THREAD

**Issue by vdurante** [Nain57/Smart-AutoClicker#15]
I am playing idle slayer and it is really hard to crop a few conditions since they happen too fast. Have you ever used ShareX? When you take a screenshot it freezes the image and lets you crop the image. Idk if it is possible to do something similar, but I was thinking about the following feature: when you open the condition crop gui you can click outside the box and it will freeze the gui on that image. You can then take your time to properly crop the image. If you click outside it unpauses the image.

What do you think? Would be possible? TIA

**Comment by Nain57** [comment]
This is a good idea, and using this kind of behaviour can also help to capture very small conditions, helping to fix other issues in this tracker.

**Comment by Nain57** [comment]
In the lastest release, I have reworked completely the click condition capture user experience thanks to your feedback: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.1.0

The capture is now splitted in two steps:

First, you have to take a full screenshot of the screen
Then, you can move the square selector as the previous version, but you can now move/zoom on the screenshot.
This should make it easier to create small or quick images for the click conditions.

Let me know if like or not this solution.
