### ISSUE TITLE
[Feature Request] Recursive Group for both Conditions & Group

### ISSUE THREAD

**Issue by faustaahmad** [Nain57/Smart-AutoClicker#150]
**Idea**
Having a Recursive Group to prevent having too many Scenarios that can do same actions in the cost of being recursive (just set the depth)

It may have a bug where an action is clicked based on a Group that met the criteria first instead of a Condition inside that Recursive Group

**Example case:**
- Same actions for all the scenarios
- `Cx` as Condition x
- `Gx` as Group x
- `Sx(Cx)` as Scenario x, trigger by `Cx`
- `AND(args)` as "All conditions", inside a scenario
- `OR(args)` as "Only one condition", inside a scenario
- `NOT(args)` as "×" Not visible, inside a condition

**Current**
```py
S1(AND(C1, C2, C3, C0))
S2(AND(C4, C5, C6, C0))
S3(AND(C5, C6, C7, C0))
```
**With Group**
```py
G1 = AND(C1, C2, C3)
G2 = AND(C4, C5, C6)
G3 = AND(C5, C6, C7)
G4 = OR(G1, G2, G3)
S1(AND(C0, G4))
```

Thanks, feel free to ask about this Idea

**Comment by Nain57** [comment]
This will not be implemented, as it goes against the principle of simplicity of this application.
Thanks for the suggestion.
