### ISSUE TITLE
App is crashing when the orientation changes from landscape to portrait.

### ISSUE THREAD

**Issue by Recress** [Nain57/Smart-AutoClicker#151]
Another thing I noticed is the Accessibility settings get unchecked on the app itself, so in a sense the crashing happens when the app's accessibility changes.

I mainly noticed this when I encounter ads on the games I'm playing, some of them are in landscape, otherwise, it crashes.

Edit: using Bluestacks btw~

**Comment by dginovker** [comment]
Not sure if this helps, but I've noticed similar problems on device with Android 11. Simply starting Smart-AutoClicker, opening a game, then going into landscape mode prevents AutoClicker from being able to do anything.

**Comment by Nain57** [comment]
New version 1.5.3 include a potential fix for this issue.
It is available [here ](https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.5.3) and on F-Droid soon.

Let me know if you still encounter this problem
