### ISSUE TITLE
[PERFORMANCE ISSUE] After longer execution, actions will be executed twice 

### ISSUE THREAD

**Issue by talka1** [Nain57/Smart-AutoClicker#153]
There are performance issues. after some time when you run your macro in a loop, the actions start to get executed twice after another.

Ex: See "Logo A" then do "Action A" one time. but after some time this will be executed two times after another.

**Comment by Nain57** [comment]
Duplicate of: https://github.com/Nain57/Smart-AutoClicker/issues/168
