### ISSUE TITLE
[Feature request]Add more functions to Intent action.

### ISSUE THREAD

**Issue by talka1** [Nain57/Smart-AutoClicker#156]
The Intent action is really good. It can open apps immediatly. It would also be nice to have an option to close selected apps.

**Comment by Recress** [comment]
Would you know if Intent actions have the option to close-open the intended app again?

**Comment by Nain57** [comment]
The full Intent API is already implemented in the application.
You can take a look at the official documentation of the intents here: 
* https://developer.android.com/guide/components/intents-filters
* https://developer.android.com/reference/android/content/Intent
