### ISSUE TITLE
Apps that block autoclickers

### ISSUE THREAD

**Issue by hamoumiKen** [Nain57/Smart-AutoClicker#157]
Hi,
Is there any way to get through an app that is blocking autoclickers?
Or will Smart auto clicker work with these anti-auto clicker apps in a future update?

**Comment by Dimava** [comment]
You can try android emulator on PC

**Comment by Nain57** [comment]
A randomization feature will be added to the next version.
This might help preventing being detected as a bot.

**Comment by Nain57** [comment]
Release 2.0.0 containing a fix for this is now available on Github and should be available soon on F-Droid.
