### ISSUE TITLE
[FR] New click types and more control

### ISSUE THREAD

**Issue by vdurante** [Nain57/Smart-AutoClicker#16]
A few ideas:

For swipe:
* Add swipe time (for long swipe actions)

For clicks:
* Add multitap feature with delay between taps 
* Hold time, allowing to click and hold

Delay between clicks:
* Split into: delay for next click of same type and delay for next click of other type

**Comment by Nain57** [comment]
Thanks for your ideas.
I tag this ticket as enhancement and I will look at it once i have some time to work on this project

**Comment by Nain57** [comment]
Enhancement implemented in v1.2.0 available here: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.2.0 or on F-Droid within a few days.
