### ISSUE TITLE
Script stops working after a while and overlay goes away, notification remains anyway

### ISSUE THREAD

**Issue by SoraRoxasVentus** [Nain57/Smart-AutoClicker#160]
I'm unsure of what the conditions are to replicate this exact issue, it happens at the most random of times, but basically after a script has been running for a while it just stops working and the overlay also goes away, depsite the notification still remaining (as you can see here:https://imgur.com/mBjwyNX )

I'm using a redmi note 9 pro, gave it all possible permissions, enabled auto start up and disabled all energy savings.

**Comment by Naze-Wazawaza** [comment]
I figured out what was wrong. Go to your device settings - > developer options - > and turn off MIUI optimization. That should fix it but you'll have to re enable all app permissions
