### ISSUE TITLE
Image Detection Resize

### ISSUE THREAD

**Issue by notyourusualuser** [Nain57/Smart-AutoClicker#162]
Can i request to make the image resizing be more flexible ? what i mean by that is theres a certain limit on how thin the image i can select. EX. HP bar image. i think this would be a simple fix if you can adjust the limit on how much we can resize it

**Comment by Dimava** [comment]
That may be intuitive (if you know what to guess) that the selection image is zoomable 
You can select a square with size down to one letter, 5 times smaller then the smallest square without zooming.  
Obviously, noone tells you about that

**Comment by Nain57** [comment]
A hint icon have been added since 2.0.0. It should be more obvious that you can pinch to zoom
