### ISSUE TITLE
Problem with image detection taking about 3 seconds.

### ISSUE THREAD

**Issue by hamoumiKen** [Nain57/Smart-AutoClicker#165]
It takes too long to detect images. The time required is about 3 seconds.
I don't know why, but it seems that some apps detect images in an instant and others take longer.
I tried various settings but the result was the same.
I wish all apps would detect images in the same instant.

**Comment by Nain57** [comment]
Hi,

Performance really depends on your scenario (and of course, your device)
On my OnePlus 7 Pro (a 3+ year old device), here are the performances measured (with the default tolerance/quality):

With a condition image of 100px/100px with lots of shapes (not uniform, i.o.w, with a lot of shapes and colors):
* Whole screen detection average time: 50ms (min: 17ms; max: 61ms)
* At position detection average time: 12ms (min: 11ms, max: 13ms)

Tips to improve your scenario performances:
* Try to move the 'time sensitive' events higher in the list
* Try to reduce the size of your scenario: 
    * if two events have the same conditions, they should be merged
    * if two events have the same actions, try to merge them if possible
    * remove any useless events in your scenario
* Condition size impact the performances of the detection differently depending on the detection type:
    * for whole screen detection, the bigger the image is, the fastest the detection will be.
    * for at position detection, the smaller the image is, the faster the detection will be.

**Comment by dginovker** [comment]
Have you tried the new slider that changes speed for accuracy?
