### ISSUE TITLE
Click offset for Image detection mode

### ISSUE THREAD

**Issue by byzod** [Nain57/Smart-AutoClicker#167]
By default autoclicker can only click predestined position when using image detect mode

But there are many scenarios that a offset is required to click correct position

For example there are many question like this:

```
1. Do you like AAA
O Yes
O No

2. Do you like BBB
O Yes
O No
```
The `O` represents a radio button

If you want to click `Yes` for AAA and `No` for BBB, it's impossible to do so without click offset, captured a image of `O Yes` or `O No` is pointless since all questions have the same answers

**Comment by hsantanna** [comment]
I built a scenario for a robot that navigates through the Instagram app and automatically blocks ads. It works incredibly well, except for the reels. In this case, the only solution would be the relative click function (click offset).

**Comment by byzod** [comment]
Why is this completed? I updated to the newest version and there's still no click offset

Yes you can now set a fixed click position, but if I already know the position to click, why do I need this at all

**Comment by Nain57** [comment]
All tickets with the old format have been closed, as the issue section needed a cleaning.

If you still think this request is relevant, please open a new feature request ticket
