### ISSUE TITLE
Frequently Double Taps. 

### ISSUE THREAD

**Issue by ZeroSaber** [Nain57/Smart-AutoClicker#168]
I really like the idea of this app and have been testing it in the current event in Fate/Grand Order and I have been a struggle because the app will frequently double tap an indicated location which is a major issue because in Grand Order there are a number of options in battle that need to be selected in sequence before they will execute and tapping on a choice again will unselect it so an errant double tap will completely ruin a click sequence.  I've sort of made it work by making a very convoluted scenario that accounts for situations where a sequence failed due to double taping but it's a real annoyance and still not perfect because I can't account for every situation that a double tap might happen at so I need to sit there and watch it to make sure some random double tap didn't ruin anything which the fact that I need to babysit it sort of kills some of the convenience.

I even tried using it in conjunction with another autoclicker that I've used successfully in the past (but can't use in every event because some farming set ups need image recognition to make the right choice to farm properly) to try and have the other clicker handle the battle and have Smart Autoclicker turn the other clicker off when it's time to make the image based choices and turn the other clicker back on afterward but that still didn't work because of the double taping.  Smart Autoclicker will just sit there double taping the play/stop button on the other Autoclicker, causing it to play and immediately stop so it can never actually get started.

**Comment by Nain57** [comment]
Hi !

Thanks for your feedback. 
It helped me to identify a possible issue with the click/swipe management. Next version should include a fix for it.

**Comment by Nain57** [comment]
New version 1.5.3 include a potential fix for this issue.
It is available [here ](https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.5.3) and on F-Droid soon.
