### ISSUE TITLE
(Not an issue) just thank you and commendation! Awesome user-friendly UI-Friendly intuitive experience for non-tech-savvy user

### ISSUE THREAD

**Issue by lpstandardrp** [Nain57/Smart-AutoClicker#169]
Hey i just want to send props and recognition for a amooth usrr experience.
I tried automation apps; I didnt have the patience, time, or learning style to  find learnimg them worthwhile. I think something about SmartAutoClicker fills a niche gap that other automation apps (that I tried a couple years ago) did not fill; it has to do (I imagine) with a logical *and* visual approach with non-abstract (i.e. non-developer | non-boolean logic-minded) feedback... 

I have tried modular coding, modular visual software (i.e. modules representing specific "code" functions that a user ties together... but, they have been taximg and just didn't make intuitive sense.

SmartAutoClicker is intuitive. It's visual feedback orientedness, and user-friendly *simple* representation (GUI) makes using and learning a breeze. I imagine it is probably a good stepping-stone into more boolean/logic/abstract/non-visual approaches to automation apps/... im not great with words so ill hope this makes sense!!!

just thank you and i send my commendations! Awesome user-friendly UI-Friendly intuitive experience for non-tech-savvy user

**Comment by Nain57** [comment]
Hi !

Thank you for your feedback. As the application is only available here and on F-Droid (which doesn't provide rating/comments), I have very few positive returns, and this kind of messages is heartwarming !

Thanks again !

**Comment by jmhjr** [comment]
I second the praise and thanks for the app and the work you do!!!!
