### ISSUE TITLE
Android 13

### ISSUE THREAD

**Issue by Schnarko** [Nain57/Smart-AutoClicker#171]
I can't do anything because of the new 'restricted settings' stuff in the new Android 13 Version. Does anybody know a workaround maybe?

**Comment by Nain57** [comment]
Hi !

I have tested only on the Android 13 emulator and didn't have this issue. 
Can you provide more explanation about it ? A screenshot of what is this "restricting settings" would be great, as I have no idea what it could be ?

**Comment by sdex** [comment]
You need to manually allow restricted settings for the app
![image](https://user-images.githubusercontent.com/3196011/191213321-4436bcd9-9307-4f81-9aea-2b885f2140c8.png)

**Comment by Nain57** [comment]
Thanks for your answer.
This was driving me crazy as I thought it was an issue from my app 😅

**Comment by sdex** [comment]
It might make sense to mention it somewhere. Android 13 comes with restrictions for the sideloaded app (not from the play store actually) and when more users get the newest OS version they will face the restrictions. 
There is a good [blog post](https://blog.esper.io/android-13-sideloading-restriction-harder-malware-abuse-accessibility-apis/) with more details.

**Comment by Hackergeek** [comment]
This video may help you to solve the problem：[https://www.youtube.com/watch?v=0bcLjpfrmHw&ab_channel=munchy](https://www.youtube.com/watch?v=0bcLjpfrmHw&ab_channel=munchy)
