### ISSUE TITLE
Bug on 1.5.3 version

### ISSUE THREAD

**Issue by PhungVietHuynh** [Nain57/Smart-AutoClicker#177]
There are a bug in the new release 1.5.3 version. The app will crash if you try to pick new image for new event.

**Comment by Nain57** [comment]
This is a known issue.
It is already fixed in version 1.5.4

**Comment by PhungVietHuynh** [comment]
> This is a known issue. It is already fixed in version 1.5.4

Thank you Nain57. I didn't know they is newer version
