### ISSUE TITLE
Image detection failure

### ISSUE THREAD

**Issue by zguinga23** [Nain57/Smart-AutoClicker#178]
Hello Nain57,
Since the last update 1.5.4, Image detection fails from time to time, let's say once every seven or eight executions, even when setting tolerance at its maximum. I've never got this problem with previous versions.

**Comment by zguinga23** [comment]
The problem occurs in 1.5.3 version too

**Comment by Nain57** [comment]
An issue related to this bug have been found, it should be fixed in the next version

**Comment by Nain57** [comment]
Release 2.0.0 containing a fix for this is now available on Github and should be available soon on F-Droid.
