### ISSUE TITLE
[FR] Add option for delay click after found image

### ISSUE THREAD

**Issue by k-y-a** [Nain57/Smart-AutoClicker#18]
Using 1.0.0.RC3, Smart-Autoclicker is really good and fast. But it too efficient in it search and clicking too fast. 

Can a delay option be added so it wait a little before click? For example: 
1. Image Found
2. Wait 500ms
3. Click

Current it is:
1. Image Found
2. Click instantly

I know there is "delay before next click", but that for repeating the next action. Thank you.

**Comment by Nain57** [comment]
That's was actually a feature in a very early stage version. I removed it because I couldn't ring a usage for it, but I will add it back to the next release.

**Comment by Nain57** [comment]
Enhancement implemented in v1.2.0 available here: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.2.0 or on F-Droid within a few days.
