### ISSUE TITLE
Is there a way to filter for intents?

### ISSUE THREAD

**Issue by Metazolid** [Nain57/Smart-AutoClicker#182]
I've been looking into intents a little bit but didn't go much further than _open app X_ when Y happens on screen.
I'd like to have a scenario set up where it automatically closes advertisements when they're done rolling but there are so many variants and placements of the close button that I thought it might be easier to just have an intent along the lines of _close finished ad_.
I thought it would be awesome to have a selection of intents to pick from for any given app that is open/active right now.
While writing this I found an App on f-droid called [Stanley](https://f-droid.org/en/packages/fr.xgouchet.packageexplorer/) that does something similar but I felt like bringing it up if it would be a feasable option to integrate that function.

**Comment by dginovker** [comment]
A generic way to close advertising would be a cool use of intents!

For me personally, I detect about 10 different "X" buttons to close ads, and also detect when an ad gets stuck and use an Intent to reopen the app. It's able to view maybe ~20 ads/hr without ever getting stuck (my current issue is Smart AutoClicker closes after ~10 hrs, trying to catch the logs for that). Maybe you could also try this in the meantime. Happy botting!

**Comment by Metazolid** [comment]
Yeah that was basically what I was going for, I thought about bruteforcing it like you with getting more or less every ad X location figured out but I felt like that's unreliable since there are so many variables, even going from landscape to portrait mode and new ads coming in every so often.

I extracted an intent list from a game (C.A.T.S. in this case) but I have _no_ clue how to make sense of the stuff that's inside. Naive me expected some command in there that indicates it can be used to close an ad as soon as it's an option, you know for rewards and stuff but no luck. ¯\_(ツ)_/¯

My best theory as a workaround right now is to open the ad and click on it after like 5 seconds. As far as I know they all open in either the Play Store or default browser which _could_ serve as some form of common denominator. Not sure if that makes any sense but that was my idea of somehow simplifying the concept.

**Comment by Metazolid** [comment]
I've found a solution, well sort of.
There is an app called [Floating Back Button](https://play.google.com/store/apps/details?id=comm.fltback.btnfloat&hl=en&gl=US) (Balint Infotech) which can be tapped on by SmartAutoClicker and moved anywhere on screen. I have made my scenario in a way that it taps on the ad, waits 45 seconds (afaik _all_ ads are about 30 seconds long) and then presses wherever I put the back button.
This essentially closes the ad and brings you back _as if_ you tapped on the X, regardless of where it was located.

I wish there was an open source alternative for that app, but I just skimmed the surface, app seems to work fine.

**Comment by Nain57** [comment]
Intent API is completely implemented in Smart AutoClicker.
You might want to take a look at the official Android documentation:
* https://developer.android.com/guide/components/intents-filters
* https://developer.android.com/reference/android/content/Intent

Please note that all application can implements their own custom behaviours on intents.
