### ISSUE TITLE
Issue with loading backup.

### ISSUE THREAD

**Issue by tosamyng** [Nain57/Smart-AutoClicker#189]
I dont know if im doing something wrong but when I save my macro as a backup and then try and load it, either on the same instance or a different instance of bluestack it does not keep the right order of my actions.

**Comment by tosamyng** [comment]
I noticed if I copy the event then the action stay in the right order when I make a backup but if I move the order of the action and then make a backup it does not save the order.

**Comment by Nain57** [comment]
The scenario saving has been overhauled. It should fix this issue on the next version.

**Comment by Nain57** [comment]
Release 2.0.0 containing a fix for this is now available on Github and should be available soon on F-Droid.
