### ISSUE TITLE
Emulator getting hung 

### ISSUE THREAD

**Issue by anthomac** [Nain57/Smart-AutoClicker#19]
I tried your app on bluestacks emulator. As soon as I start capture after providing accessibility and overlay permission entire emulator is hung and not responsive.  Only way to get bluestack instance to run again was to kill bluestacks app from windows and restart it.

**Comment by anthomac** [comment]
Sorry for reopen state. I accidentally closed it

**Comment by Nain57** [comment]
[Smart-AutoClicker 1.2.3](https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.2.3) is now available. It should fix this issue.
The update should be available soon on F-Droid.
