### ISSUE TITLE
Minimum height and width of an image captured a little big

### ISSUE THREAD

**Issue by dvhamham** [Nain57/Smart-AutoClicker#192]
I want to take small pictures so that in the proposed profit exceed the aspects of the picture that I want to work on if it was possible to make the height and width less.

In this picture, I want to capture only the orange part, but the suggested square is bigger

![Screenshot_20221028-101127](https://user-images.githubusercontent.com/23020422/198551328-149b4725-0bba-46bf-aedb-fba954d62762.png)

**Comment by hhhvfclowmn** [comment]
bump

**Comment by jmhjr** [comment]
This is possible by zooming in on the section of screen you want to capture. The capture box will stay constant, however the picture will increase in size. Just pinch and zoom on the screen.

**Comment by Nain57** [comment]
As suggested in the post above, you can pinch to zoom to capture a smaller condition.

Next major release will include a hint for this gesture, as well as the possibility to capture an even smaller condition.
