### ISSUE TITLE
[Feature request] Auto start scenario when app is launched.

### ISSUE THREAD

**Issue by jmhjr** [Nain57/Smart-AutoClicker#194]
This would be great to have for when the device is set to automatically reboot on a frequency. It could get right back to doing what we have configured, without intervention.

**Comment by tosamyng** [comment]
This sounds nice hope we get it.

**Comment by Nain57** [comment]
Starting the application request the screen casting permission.
This is mandatory in order to ensure the users that the application doesn't keep recording the screen while stopped.
