### ISSUE TITLE
Crashing during usage randomly and Accessibility permission issue

### ISSUE THREAD

**Issue by OutStrawX** [Nain57/Smart-AutoClicker#195]
My phone is a redmi 9 and while I am running the auto clicker it just randomly closes completelt, when I try to re-open the application and start the overlay, it gives me a popup saying that I need to **provide accessibility permissions** to the app which I already have, then I go back to the app and its still not working, I have restarted my phone and it worked just until it crashes again. I have tried **versions 1.2 up to 1.5** and there is no difference in issues.

**Comment by Nain57** [comment]
Duplicate of https://github.com/Nain57/Smart-AutoClicker/issues/161
Also, 1.5.0 up to 1.5.4 versions have been focused on stability improvements. You might to take a look at the most recent versions.
