### ISSUE TITLE
Overlay Control is not touchable in android version 7.1.2

### ISSUE THREAD

**Issue by anthomac** [Nain57/Smart-AutoClicker#20]
In my android mobile which is having android version 7.1.2 after starting capture service I get overlay control nut its not interactable.
any touch input on overlay control is triggering actual item behind it but not activating overlay control.

If you want to reproduce you can try emulator from android studio. there also I got same issue of overlay not touchable.

**Comment by Nain57** [comment]
Issue fixed by RC4: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.0-RC4
