### ISSUE TITLE
Problem with redmi note 8 pro xiaomi

### ISSUE THREAD

**Issue by Risistas** [Nain57/Smart-AutoClicker#210]
Hello ou bonjour (si tu es fr)

I have try to use the app, and she work nice but i have a problem with accessibility
I have disable mui optimization 
No battery lock 
My version is MIUI global 11.0.5
Version Android 9 PRPR1

I dont understand for what they dont work, they work only if battery are in charge. 

Thank you for your Help.
Have a good day.

![Screenshot_20230117_141223_com android gallery3d](https://user-images.githubusercontent.com/122886277/212907908-0a7db8ad-33e4-4b62-a702-9c560074e3bf.jpg)
![Screenshot_20230117_141221_com android gallery3d](https://user-images.githubusercontent.com/122886277/212907914-98ad5348-7d6d-4993-b230-0a883286590f.jpg)

**Comment by Nain57** [comment]
Hi.
On Android versions below 13, the accessibility setting seems to be misfunctioning. You might need to enable it, disable it and then re-enable it.

**Comment by BilliBoleMeow** [comment]
Go and tuen on auto start permission for the smart auto clicker, it's an known issue in miui for any app that require accessibility function
