### ISSUE TITLE
[Feature Request] Option to Play Events in Order (Top to Bottom)

### ISSUE THREAD

**Issue by Cananbolt** [Nain57/Smart-AutoClicker#222]
First, thanks for the amazing app, it's a real game changer!

One request that I would like to make is that the events play in order.

Example:
There are 3 events

A
B
C

Events A and C are in the same page but they are set at different conditions and different actions

However after event B finishes, because both events A and C can be found on the same page it prioritizes event A.

**Comment by Nain57** [comment]
Version 2.0 will add a new action allowing to control an event state.
You will be able to enable, disable or toggle the state of another event in order to control which event must be interpreted at any time.

**Comment by Cananbolt** [comment]
Sounds great, thanks for the hard work

**Comment by Nain57** [comment]
Release 2.0.0 containing a fix for this is now available on Github and should be available soon on F-Droid.

**Comment by Cananbolt** [comment]
Unfortunately it did not work for me.

The scenario is...

Clicks A
B appears on the same screen as A
Still Clicks on A

I tried all the event states for both A and B, individually and together but it still did not work.
