### ISSUE TITLE
[Bug] MainMenu.kt , debug window visibility setting not work util Orientation Changed

### ISSUE THREAD

**Issue by laiqun** [Nain57/Smart-AutoClicker#224]
```
//File : MainMenu.kt
    override fun onCreate() {
        ...
        viewBinding.layoutDebug.visibility = View.GONE //This line not working util orientation changed.
}

```
```
    private fun updateDebugOverlayViewVisibility(isVisible: Boolean) {
        if (isVisible && debugObservableJob == null) {
            viewBinding.layoutDebug.visibility = View.VISIBLE   //This line not working util orientation changed.
            setOverlayViewVisibility(View.VISIBLE)
            debugObservableJob = observeDebugValues()

        } else if (!isVisible && debugObservableJob != null) {
            debugObservableJob?.cancel()
            debugObservableJob = null

            viewBinding.debugEventName.text = null
            viewBinding.debugConditionName.text = null
            viewBinding.debugConfidenceRate.text = null
            viewBinding.layoutDebug.visibility = View.GONE //This line not working util orientation changed.
            setOverlayViewVisibility(View.GONE)
            (screenOverlayView as DebugOverlayView).clear()
        }
    }
```

**Comment by laiqun** [comment]
reproduce step:
1. Change overlay_menu.xml, and set debug window to visibility.
2. Start Scenario 
3. You can see debug window still show in the floating window(MainUI).

4. Shutdown lock orientation setting.
5. Open chrome or Firefox for android. Or any app can change orientation.
6. Change the orientation.
7. You will not see debug Window now.

**Comment by laiqun** [comment]
I think there are some conflicts with the animation of mainUI.
Since we can change visibility setting when overlay window added.
How about transfer debugWindow enable state at creating operation.
```
                rootOverlayController = MainMenu(this@SmartAutoClickerService, scenario.id, enableDebugWindow).apply {
                    create { this@LocalService.stop() }
                    show()
                }
```

**Comment by Nain57** [comment]
Is this issue happening on master or 1.5.4 ?
I have reworked the window and I can't reproduce it

**Comment by laiqun** [comment]
@Nain57  Master. 
May be caused by the android version change. 
I have updated my phone to android 13.
This is not a matter issue, if can't reproduce on your phone, please ignore this issue.

**Comment by Nain57** [comment]
Not reproduced on my devices on Android 13, Android 12, Android 8.

I will try to take a look on emulator

**Comment by laiqun** [comment]
![debugwindow](https://user-images.githubusercontent.com/13235080/218316266-9156d51e-7516-4010-aa54-5098c1f1298a.gif)

**Comment by laiqun** [comment]
Add gif.

**Comment by Nain57** [comment]
I really don't get how you reproduce this, have you changed something in the code in your gif ?

This black window on the right of the menu is not the debug overlay but the full size of the overlay that changes during the play pause animation (this is a required trick to correctly animate the window during the transition)

The debug overlay is only supposed to be shown while a scenario is playing. Here is the expected result:

Pause state:
![Screenshot_2023-02-12-21-22-41-77_b783bf344239542886fee7b48fa4b892.jpg](https://user-images.githubusercontent.com/8599025/218335149-9fea7fa3-9b11-4ce8-9a4c-c3d9487909b0.jpg)

Play state with something detected:
![Screenshot_2023-02-12-21-22-50-03_b783bf344239542886fee7b48fa4b892.jpg](https://user-images.githubusercontent.com/8599025/218335175-22a79a66-c9d1-4221-9fc6-a6519c7a949d.jpg)

**Comment by laiqun** [comment]
I will try it on emulator.

**Comment by laiqun** [comment]
I have tried on emulator.  It's look OK now.
But the pause button maybe stuck. is this a known issue?

**Comment by Nain57** [comment]
I still don't get it, how the bug is not reproduced anymore ?
Are you modifying the code ?

If that's the case, do not open a issue ticket, they are reserved for the application.
