### ISSUE TITLE
Android 13 Crash

### ISSUE THREAD

**Issue by Arr4y** [Nain57/Smart-AutoClicker#225]
I recently updated to android 13. It crashes as soon as I press record screen. Additionally, I needed to disable and re-enable the accessibility service as it didn't detect it when I first opened it up and it asks for it again after force-closing it when it crashes.

**Comment by o-data** [comment]
Apparently this got to do with Battery Optimization, see if that is the case for you. I'm having some issue but yet to find solution for it.

**Comment by Arr4y** [comment]
> Apparently this got to do with Battery Optimization, see if that is the case for you. I'm having some issue but yet to find solution for it.

No, not at all. Everything was disabled and crashing was instant. But the latest release fixed this issue.

**Comment by o-data** [comment]
That surprising, perhaps you will run into my next issue instead. Accessibility service stop working, so you have to disable and renable it.
