### ISSUE TITLE
On condition, exit auto-clicker

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [Nain57/Smart-AutoClicker#227]
Can we have an action to exit the autoclicker?

**Comment by Nain57** [comment]
Scenario End Condition already fulfill this feature.

**Comment by SodaWithoutSparkles** [comment]
Found it. Thanks!

Would it be better to guide users to said feature?

**Comment by SodaWithoutSparkles** [comment]
@Nain57 It just pauses the execution, not end the autoclicker. I was hoping something like pressing the square button
