### ISSUE TITLE
[Feature] Simple Auto Click (maybe with counter)

### ISSUE THREAD

**Issue by KiritoStorm** [Nain57/Smart-AutoClicker#23]
I know the App is callled Smart Auto Clicker, but I think that sometimes a simple click one point would be usefull.
It's sometimes hard to find a picture that's allways detected as unique, so it would be useful for task like click 50 times on this point.

And thank you for building this app, it's really great. ❤️

**Comment by yuanlk** [comment]
I second this, it's pretty frustrating having to add image every time when all I needed is a simple tap.
