### ISSUE TITLE
Allow back gestures to be used

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [Nain57/Smart-AutoClicker#232]
When the settings overlay is on screen, we cannot use the full-screen back gesture to navigate. Only the back button in the overlay works. Which takes some time to get used to.

**Comment by SodaWithoutSparkles** [comment]
https://user-images.githubusercontent.com/64138578/221344877-367122e5-862e-4f00-99e1-ec7a37b9c7cc.mp4

**Comment by Nain57** [comment]
Back gestures works fine on Pixel 6 and OnePlus 11.
Unfortunately, this issue seems related to your device behaviour with dialog overlays.
