### ISSUE TITLE
Add monochrome icon 

### ISSUE THREAD

**Issue by xmha97** [Nain57/Smart-AutoClicker#233]
Please add support for the Android 13 "Themed Icons".

![Screenshot_2023-02-25-19-21-58-380_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/221366513-2dd624aa-bb1d-4f50-b71a-5cafded7417f.jpg)

**Comment by Nain57** [comment]
Added to next version roadmap.
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by Nain57** [comment]
This should be supported with the latest version (2.0.2), already available [here](https://github.com/Nain57/Smart-AutoClicker/releases/tag/2.0.2), or soon on F-Droid.
As I don't have a pixel phone, I can't check if this is completely OK, but I have completely implemented the Google guidelines.

If someone can confirm this is functional, I will close this ticket.

**Comment by xmha97** [comment]
Ok, thanks 👍

![Screenshot_2023-03-05-23-16-36-195_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/222982288-0b1f1c04-ed74-4db1-b713-7a0969103976.jpg)
