### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by xmha97** [Nain57/Smart-AutoClicker#235]
Hi, the button is very bottom!

![Screenshot_2023-02-25-19-21-47-080_com.buzbuz.smartautoclicker.jpg](https://user-images.githubusercontent.com/23485114/221366550-39f6a46e-1b42-4a8d-b093-575dc7a5bbae.jpg)

**Comment by Nain57** [comment]
Already fixed in 2.0.1. Version is currently building and should be available soon

**Comment by xmha97** [comment]
Thanks 🙏
