### ISSUE TITLE
Pause and play stops working

### ISSUE THREAD

**Issue by LostLinguine** [Nain57/Smart-AutoClicker#237]
When playing and pausing a macro the pause button stops working after a few pause and play button presses, requiring you to go back into the app and play the macro again to stop it.

**Comment by Nain57** [comment]
Hi.

Please provide more information:
* Android OS version
* Device brand and name
* Configuration of the issue (debug view/report enabled...)
* The .zip of the exported scenario causing the trouble
* Screenshots of the issue

**Comment by LostLinguine** [comment]
•android 11
• happens on my tcl a3x(a600dl) and my galaxy A01
•i usually have debug view enabled but not report
•[SmartAutoClicker-Backup.zip](https://github.com/Nain57/Smart-AutoClicker/files/10831907/SmartAutoClicker-Backup.zip)
•
![Screenshot_2023-02-25-10-47-03-443](https://user-images.githubusercontent.com/125235925/221372105-6ac797e0-7a04-448c-bbfb-7c8dacf2a3bd.jpg)

After I play the macro, pause it, then play it again clicking pause doesn't do anything and I can't move it either but the macro still works.

**Comment by Nain57** [comment]
Fixed in version 2.0.2, available [here ](https://github.com/Nain57/Smart-AutoClicker/releases/tag/2.0.2)or soon on F-Droid.

**Comment by LostLinguine** [comment]
Don't know how I did it before but I can't upload the ZIP file so I'll just use my Google drive to give you the file in question.

https://drive.google.com/file/d/18Duh7tPtMjLlBrCYtnZDhHWJkGGhC_78/view?usp=drivesdk

When the macro does 1 full cycle the event "stop inviting me" somehow gets higher priority than "alt" after the alt event gets enabled and disabled.. I think "skip battle" event sees a condition that is on the screen at the same time as the events get enabled/disabled and that somehow messed up what event gets prioritized over the other. I use that "skip battle" event to tap on screen to skip slow animations so it's bound to have to be used while an event is being enabled and disabled so it needs to be able to get around this issue.

Steps to reproduce:
Can't say for certain since I'm not sure what is causing this issue but from my experience it needs at least 4 events but I'll do my best to explain what happens
1. Skip event (near constantly clicks)
2. The event that gets enabled and disabled by another event(doesn't disable itself)
3. An event that doesn't ever get disabled or enables/disabled another event
4. An event that disables event 1 but not itself
5. (Order of events: event 2, event 4, event 3, event 1)
6. Event 2(triggered 1 time)->event 1 then clicks to skip -> event 4 triggers-> event 3 then has priority over event 1 for some reason even though it's the last or even 2md to last in sequence of actions.

-Device: tcl a3x
-Android version: 11
-Smary clicker version:2.3.2

Hope this helps with fixing the issue, don't know why else an event would lose priority in sequence just from having an event click on screen passively the same way a simple clicker + smart clicker would do but if I can help get this fixed then it'll make smart clicker better for those specific use cases.
