### ISSUE TITLE
Pointer not showing and greyed out start button.

### ISSUE THREAD

**Issue by Thewisem** [Nain57/Smart-AutoClicker#24]
When I click the autoclicker from the board, it will say starting and sjow an option. But there is no pointer and I can't click on any of that option.
Device: Samsung Galaxy Tab A
OS: Android vr 7.1.1

**Comment by Nain57** [comment]
Are you using the version 1.0.0-RC3 ? There was an issue on that version preventing users on Android 7 to click on the overlay menu.

This has been fixed on RC4 which should be released on FDroid in a few days

**Comment by Thewisem** [comment]
Oh ok. Yes I am using rc3

**Comment by Thewisem** [comment]
On fdroid
