### ISSUE TITLE
Larger Play button and further away, possible if/else/then logic

### ISSUE THREAD

**Issue by lumixx** [Nain57/Smart-AutoClicker#240]
Make the side bar Play/pause button larger and distinct, further away from the rest ones to avoid misclicks and accidental exit,  thus reducing anxiety😀.

If possible, a form of if/else/then logic in the command flow.

**Comment by Nain57** [comment]
The buttons are respecting the standard Material design size and spaces, furthermore, using a bigger bar will cause Android 12+ to trigger its security against malicious inputs.

No if else logic as well, as the aim of this software is to stay simple and accessible to regular users
