### ISSUE TITLE
Floating keyboard stays on screen

### ISSUE THREAD

**Issue by shmaungms** [Nain57/Smart-AutoClicker#242]
When editing an event or adding a new event to a scenario and you are changing the name for the event the only way to dismiss the floating keyboard is to click on conditions or actions buttons. Clicking elsewhere on the screen or on the conditions box or state box does not make the keyboard disappear. 

In this screenshot clicking on the state box brings up the enable/disable selections but the keyboard is still there.
![Screenshot_2023-03-06-10-24-21-79_aebe98ad7d7a8529ca6c0fe655bccdd7](https://user-images.githubusercontent.com/120090978/223056315-64849040-300e-4378-82ff-990b13096e18.jpg)

Device Oneplus Nord 2 5G

**Comment by Nain57** [comment]
This should be fixed by https://github.com/Nain57/Smart-AutoClicker/commit/975b23e8d0c3e958efb4424f2074c0e7505e986d.

Now, clicking on another item should close the keyboard. Also, correct text/number keyboard is displayed, and "Done" button closing the keybaord is now shown.
