### ISSUE TITLE
Create a new copy of an entire scenario

### ISSUE THREAD

**Issue by shmaungms** [Nain57/Smart-AutoClicker#243]
I'd like to be able to create a new copy of an entire scenario.

My reason is I have a scenario with about 19 different events. I would like 7 of these scenario's with each of them containing 5 events which are different.

1. I could use the enable/disable function ( Which was on my wish list for the app, thanks) but in this case that will be a little annoying to keep changing 5 to be enabled and 5 to be disabled.
2. I could copy the 14 I want to still use one by one in to a new scenario and then recreate the other 5 which will be a bit fiddly and time consuming especially as I would like to do it 6 times.

Thanks

**Comment by palmuse** [comment]
I would also like to see this. I would like to run the same sequence but have alternate versions of it (ex. run 5x, 10x, etc). Would be great to beable to copy entire scenerio and edut parameters. I see this is using json, so i may try to manually edit a backup to creat additional versions.

**Comment by shmaungms** [comment]
I have just discovered how to do this. Save a backup of just the one scenario you want to copy and then import it back again. There's now a copy of the scenario!
