### ISSUE TITLE
Bot can't start

### ISSUE THREAD

**Issue by sipome** [Nain57/Smart-AutoClicker#244]
Describe the bug :
Accessibility permission issues

1. Open aplication
2. Click play button
3. Error message appear
4. See screenshot attachment

Sreenshots on my device problem :

![Screenshot_20230313_235912_Device care](https://user-images.githubusercontent.com/72540448/224761209-911eff46-ce69-4631-8f5b-af7077a1604d.jpg)

![Screenshot_20230314_000510_Smart AutoClicker](https://user-images.githubusercontent.com/72540448/224764530-d0b8712d-6c8c-455b-a36d-12d62b189cf4.jpg)

This message always appears even though accessibility permissions have been allowed

Smartphone :
 - Device: samsung galaxy A13
 - Android OS version: Android 13
 - Smart AutoClicker version  2.0.2

**Comment by Nain57** [comment]
When you say "Click play button", you mean the one in the Scenario selection screen or the one in the menu ?

If that's the second case, I will need the zip file of the problematic scenario, can you provide it ?

**Comment by Nain57** [comment]
Closed: Old bug format and stability have improved since. If you still have the issue, please open a new ticket.
