### ISSUE TITLE
Can't copy an event with a toggle event action

### ISSUE THREAD

**Issue by shmaungms** [Nain57/Smart-AutoClicker#247]
I was trying to copy multiple events into a new scenario but was unable to copy the two events that had a toggle event action within them. If I tried copying multiple events at the same time it would crash the program and stop the accessibility service working. If I tried copying them one at a time it just closed the program and didn't copy the event.

I was able to copy to two scenarios by removing the toggle event action, copying it and then adding the toggle event back again.

Oneplus Nord 2 5G

**Comment by Nain57** [comment]
Hi and thank you for your contribution!

There is indeed no code handling correctly the copy of an event with a toggle event action. If you copy one from another scenario, it is impossible to determine what was the target of the toggle event, and that why it is crashing.

That's an issue and i'm currently working on a solution, probably a warning dialog when copying that the action needs to be edited.

**Comment by Nain57** [comment]
Should be fixed by https://github.com/Nain57/Smart-AutoClicker/commit/fa88c8d9e2d29a08775ab846f4a80db57e9a0a60
