### ISSUE TITLE
Option to use autoclicker without condition

### ISSUE THREAD

**Issue by Thewisem** [Nain57/Smart-AutoClicker#25]
I want to use autoclicker by pointing the pointer and just start autoclicking. It would be helpful if we could start autoclicking without any conditions. And with a pointer to indicate where it is being clicked

**Comment by Nain57** [comment]
This is not the aim of this application, as it already exists a lot of applications doing that.
This might be taken into consideration in an eventual future release.

**Comment by Thewisem** [comment]
I mean yes it exists bu5 not in a trustable way or open source format

**Comment by K3XRad** [comment]
In my case, I can't use Smart-AutoClicker without this feature. So I'm just waiting when it will be added. It is better for me to wait, than use untrustworthy proprietary autoclicker.
