### ISSUE TITLE
Enhancement: text input

### ISSUE THREAD

**Issue by SlavaPVR** [Nain57/Smart-AutoClicker#250]
Thank you so much for this app.

Very lacking action, text input.

And as an additional feature, cyclic input of one line of text from the list (with the action the first line from the list, with the repeated action the next line from the list).

**Comment by sunk818** [comment]
This sounds like three enhancement requests... 1) for static text input, 2) for loops, and 3) for processing a list of text. You do realize there are other tools like Macrodroid or Tasker that already do this. Having said that though, I do appreciate the idea of text input. 

* log into a web site
* change a setting on multiple accounts
* mark messages as read
* buy stocks on multiple accounts

**Comment by lipnotic** [comment]
Please!

**Comment by pwqw** [comment]
+1
a humble solution that I can think of is:

1. Save the current clipboard content.
2. Replace the content of the clipboard with what is `configured` in the `Action`.
3. Execute a "paste".
4. Restore the content of the clipboard (1)
:laughing:

**Comment by fazlerabbi37** [comment]
@Nain57 I was looking forward to this and I see this is now closed as complete. :smiley: Do we expect to see this in the next release?

**Comment by Nain57** [comment]
I have cleaned all issues and feature request that were not using the new templates.

If the request is still relevant, please create a new ticket following the new convention
