### ISSUE TITLE
Multiple states

### ISSUE THREAD

**Issue by qadeer819** [Nain57/Smart-AutoClicker#252]
How can I add following 
Use this to set up different have different state situations in absolute. There are seven stops. Let's say the first condition is found and the second condition is visible. When the second condition is clicked, it doesn't need the first

**Comment by pyjserv** [comment]
I also thought about the same issue. Maybe Smart-AutoClicker can add conditions of if events executed in the event's conditions list mixed with photo detection conditions, than the "Change event state" can add two state of "Add executed" and "Clear executed" in Actions list.  Thus some events can execute when one event is executed and some events can be disable if two events are not all executed. The scenario will be more structural.

**Comment by Nain57** [comment]
Previous answer is correct.
This feature UI needs a bit more attention, I find it complicated to change multiple events state. I will try to find something better for it.
