### ISSUE TITLE
"Intent" Actions cannot be deleted

### ISSUE THREAD

**Issue by null-dev** [Nain57/Smart-AutoClicker#253]
**Describe the bug**
"Intent" Actions are missing the delete button.

More specifically, after this line:

https://github.com/Nain57/Smart-AutoClicker/blob/fc254258d01831bc5cf5312b722cc162e68c4684/smartautoclicker/src/main/java/com/buzbuz/smartautoclicker/overlays/config/action/intent/IntentDialog.kt#L59

you are missing:

```kotlin
topBarBinding.setButtonVisibility(DialogNavigationButton.DELETE, View.VISIBLE)
```

**Comment by Nain57** [comment]
Hi and thanks for your contribution !

My Ui code can be a mess sometimes, thank you :)
This should be fixed by: https://github.com/Nain57/Smart-AutoClicker/commit/e11ed92b5455fc7fe7e3de3a9693c4cf2407d50c
