### ISSUE TITLE
Sequenced conditions and actions

### ISSUE THREAD

**Issue by LostLinguine** [Nain57/Smart-AutoClicker#257]
![Screenshot_2023-04-23-19-43-09-336](https://user-images.githubusercontent.com/125235925/233881413-66eddb18-6370-4cc3-adf4-5fd0f15b7b91.jpg)
Currently I can't find a way to have similar conditions that are on the same screen actuate in sequence, since they are all on the same screen it just clicks every condition.

What I'm suggesting is that there should be a easy way to click on exact or similar conditions on different parts of the of the screen one after the other, so as to avoid clicking the wrong condition at the wrong time, I think this could work well with zakius's " click on condition with multiple conditions required " issue

I hope I explained it well enough, but it would be nice to know if this is something that is possible to implement because it could make for some very useful auto clicker for ev training or other complicated automated tasks

**Comment by Nain57** [comment]
Hi, and thanks for your contribution.

I'm not sure to understand what you are trying to achieve. What are you trying to execute exactly on that screen ?

**Comment by josephg5** [comment]
I would like this too, if I understand op. I hope I can explain my requirement correctly.
I would like to have a scenario which checks for events sequentially only, and the same for conditions. They should run according to listed order, and the next one should not happen if previous event or condition did not happen.

**Comment by shmaungms** [comment]
There is the change event state option in an event. When the event runs you can use it to enable another event. Not sure this helps the original poster but it may work in your case.

**Comment by LostLinguine** [comment]
> 

From the top of the 5 mortys down.
After the first Morty is dazed i want it to click on and switch to the second morty, after the second Morty is dazed i want it to click on and switch to the 3rd morty, and so on.. until i get to the 5th morty, i want the 5th Morty to run from the fight.
Thats the order i want it to go in sequence. It's possible to do it by disabling/enabling conditions in the right way to prevent it from clicking on the wrong condition at the wrong time but it can take a long time to setup, and keeping track of it can be difficult as well if your having to do it for a lot of actions than need to be executed in a sequence, especially if all conditions are on the screen at the same time. The photo i put up is a good example of this.

**Comment by shmaungms** [comment]
I understand it more now. All the morties above are selectable and you want to select them in order.
1. Does the screen look 100% the same even when the first morty is dazed? 
2. The program does seem to mainly execute in order. (not 100% sure as I get it to click on 4 things that are actually moving so it can take a while to regognise it but it normally still does them in order) Maybe adding a wait after the click will stop it clicking again too quickly.

**Comment by LostLinguine** [comment]
> I understand it more now. All the morties above are selectable and you want to select them in order.
> 
> 1. Does the screen look 100% the same even when the first morty is dazed?
> 2. The program does seem to mainly execute in order. (not 100% sure as I get it to click on 4 things that are actually moving so it can take a while to regognise it but it normally still does them in order) Maybe adding a wait after the click will stop it clicking again too quickly.

1. Yes, the only thing that changes when a morty is dazed is the hp will be 0 and grey instead of green
2. Im not sure how it works exactly but from my experience it would just click all of the conditions rapidly (because i set press duration to 1) and randomly if the conditions arent enabled/disabled properly.
3. Its possible to do what i want it to do by having 5 separate attack conditions, and 4 separate switch morty conditions. The switch mortys conditions, and 4 of the 5 attack conditions are disabled by default. the first attack condition will enable the first switch mortys condition, then when the switch mortys condition is seen it will disable the first attack condition and enable the second attack condition, when the second attack condition is seen it will disable the first switch mortys condition and enable the 3rd switch morty condition, etc.. until it got to the jesus morty then it would disable whatever condition needed to be disabled but you can enable the first attack condition when the jesus condition is enabled so it can repeat in an infinite loop, and then leave. It took me a while to wrap my head around it but when i tried it it worked well and opened up a lot of opportunities, but it does create a lot of conditions and complicates things a bit.

**Comment by shmaungms** [comment]
I'm glad you got it worked out. It can be complicated to get things working, especially when you are in an in game situation an lots of things are happening.

Now that you have described how the screen changes I think I would have set it up slightly differently.
1. I would have a condition that detects just part of the green bar on the first morty and then selects the first morty.
2. The next condition would be for the second morty and it would require detecting both a grey bar on the first morty and a green bar on the second morty before selecting the second morty. (conditons all)
3. The next condition would look for a grey bar on the first and second morty and a green bar on the third morty and then select the third morty.
4. etc
This requires you to play through once setting up the conditions detections as you go but means you don't have to enable/disable events.

As for your note about clicking on all the conditions rapidly:
You can add a wait after the click to slow down the program clicking on repeatedly on a condition being met. I have found it a good idea to do this just to help stop things going wrong.

**Comment by LostLinguine** [comment]
> I'm glad you got it worked out. It can be complicated to get things working, especially when you are in an in game situation an lots of things are happening.
> 
> Now that you have described how the screen changes I think I would have set it up slightly differently.
> 
> 1. I would have a condition that detects just part of the green bar on the first morty and then selects the first morty.
> 2. The next condition would be for the second morty and it would require detecting both a grey bar on the first morty and a green bar on the second morty before selecting the second morty. (conditons all)
> 3. The next condition would look for a grey bar on the first and second morty and a green bar on the third morty and then select the third morty.
> 4. etc
>    This requires you to play through once setting up the conditions detections as you go but means you don't have to enable/disable events.
> 
> As for your note about clicking on all the conditions rapidly: You can add a wait after the click to slow down the program clicking on repeatedly on a condition being met. I have found it a good idea to do this just to help stop things going wrong.

I like your idea, having 2 conditions be visible for it to click is a great idea and could make the process a lot simpler, the only thing that wouldn't be needed is clicking on the first morty to switch.. in this game when a battle is started the first morty in you deck ( the morty on top) is automatically put into battle so you dont need to select it at all, but your idea will still work since the first morty will be dazed the second morty conditions could be seen allowing for it to work as intended, ill have to experiment more with this concept but it has good potential. Thank you for an interesting idea that i wish i thought of sooner lol.

**Comment by Anuragroyan** [comment]
Identify and prioritize conditions: First, identify the conditions you want to click on. Prioritize them based on their importance or the sequence in which they should be clicked.

Implement a sequence manager: Develop a mechanism to manage the sequence of clicks. This could be a simple list or queue where you store the conditions in the order they should be clicked.

Click based on the sequence: Iterate through the sequence and click on each condition one after the other. Ensure that you wait for each condition to appear before attempting to click it.

Handle errors and interruptions: Implement error handling to deal with cases where a condition may not appear or clicking fails for some reason. You may need to adjust the timing or implement retries in such cases.

Update the sequence dynamically: If conditions change dynamically during the process, update the sequence accordingly to adapt to the changes.

you can also try to make buttons disable or enable based on conditons.
