### ISSUE TITLE
an invisible skeleton debug window after toggle debug off

### ISSUE THREAD

**Issue by TWT233** [Nain57/Smart-AutoClicker#258]
**Describe the bug**
as title, and the skeleton window mask the underlying touching area

**To Reproduce**
1. turn on debug window
2. save, and running scenario for some time
3. turn debug off
4. the gray debug window disappears, but the area belonged to it cannot be touched

**Expected behavior**
no skeleton window

**Detection scenario**
seems not scenario related

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: samsung s20 5g(SM-G9810)
 - Android OS version: 13 with OneUI 5.1
 - Smart AutoClicker version: 2.0.2

**Comment by Nain57** [comment]
Hi and thanks for your contribution!

I'm unable to reproduce this issue, can you provide a screenshot because i'm not sure to understand what is the "skeleton window"

**Comment by Nain57** [comment]
I was finally able to reproduce it.
This should fix it: https://github.com/Nain57/Smart-AutoClicker/commit/8cb2a48ac7b17c360086c864dd4119ae6c38462e

**Comment by TWT233** [comment]
sorry for my poor description and thx for ur fix ❤️
