### ISSUE TITLE
Clicker stopping on Bluestacks/Accessibility Shortcut 

### ISSUE THREAD

**Issue by MomanNoamm** [Nain57/Smart-AutoClicker#259]
**Describe the bug**
I’ve seen other reports about this bug but none of the solutions I’ve seen have worked for me. When a script has been running for a random amount of time, it stops working.
The notification is still there but the menu is gone and it stops clicking.
Sometimes when I go back to restart the script it’ll say that it’s missing a permission and I’ll have to remove all the permissions and give them back to fix that.

**To Reproduce**
1. Use the clicker for a random amount of time
2. It stops working
3. Go to restart it and sometimes it needs permissions it should already have

**Expected behavior**
It to keep working, and to not need permissions again.

**Detection scenario**
Provide the scenario causing the issue by creating a zip file using the export feature in the application.
*in reply

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Bluestacks 5 (5.11.50.1017)]
 - Android OS version: [e.g. Android 7.1.2]
 - Smart AutoClicker version [e.g. 2.0.2]

Last month I used the same software for the same purpose and it worked better but still stopped a little. The only major changes were that I had to add some more events to the scenario.
A lot of solutions I saw mentioned things that weren’t in the settings on bluestacks. The only thing that I could find in my settings was to turn off battery optimization for the apps I was using.

**Comment by MomanNoamm** [comment]
[Uploading pseudowithswitching.zip…]()
The scenario:

**Comment by Nain57** [comment]
Closed: Old bug format and stability have improved since. If you still have the issue, please open a new ticket.
