### ISSUE TITLE
[Feature Request] Can we have other types of conditions? (Mouse and Keyboard inputs)

### ISSUE THREAD

**Issue by GabrielSk82020** [Nain57/Smart-AutoClicker#262]
Hi, I was wondering we could have the feature to add Mouse or Keyboard inputs to perform actions instead of image detection. Im not sure how much trouble/work would this feature add to the project, Im looking for a auto clicker to convert mouse inputs into clicks on specific coordinates on screen, like scroll Up would click at x:100 y:150, I'm prety awear that if this 'service' is running the mouse would stop working normaly and would only execute the simulated clicks and thats what I need, I'm playing arround with the project by myself but since I'm not an app developer I struggle a lot to make a little bit of progress.

**Comment by Nain57** [comment]
Hi.
Smart Autoclicker is for automation. Executing something else when a input is detected is more something like an InputManager or a Controler Software. This will not be integrated.

This is not a "bug" => Won't fix
