### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by PaulWoitaschek** [Nain57/Smart-AutoClicker#264]
Hey Kevin,

first of all thanks for your app - it's great. And as the permissions you need to grant to it are so powerful I would not trust any non open source app.
I read your release notes and wondered: Did you consider applying for the Github sponsorship program? That could be a way for people to show some monetary appreciation without the need of Google (and without Google taking their share of the subscriptions)

**Comment by Nain57** [comment]
Hi,

I wasn't aware of Github Sponsors, I might take a look at it !
