### ISSUE TITLE
Add Notification to Action types

### ISSUE THREAD

**Issue by shmaungms** [Nain57/Smart-AutoClicker#266]
Sometimes when using auto clicker a condition occurs that I need to manually attend.  In my case I need to open a crate and keep what I want and scrap what I don't.  Given there are 100's of possible items this can't be automated.

For me this situation happens somewhere between 3 and 12 minutes. If I can see my phone screen easily it's no problem but otherwise I have to keep going to check my phone to see if it playing the game or if I need to open a chest. 

Therefore I would find it very handy for my phone to play a notification sound to alert me I need to attend to it. I thought this option could be added as an action type.

**Comment by SledgeHunter** [comment]
Hello,
For me it would also be something very interesting. I have tried to do it with intents, but I have not succeeded.
android.media.action.MEDIA_PLAY_FROM_SEARCH
I support the idea of including an action that alerts with some sound.
Thanks

**Comment by SteegHobland** [comment]
So, now that it's completed, how do you do a notification with Klick'r?
