### ISSUE TITLE
[Feature Request] Add shoutcut toggle in notification/quick tile .

### ISSUE THREAD

**Issue by 3ekodomo** [Nain57/Smart-AutoClicker#269]
Hi there ! 
Smart autoclicker is app i searched for ! And works great. But, a feature like quick tile that will start scenario will be great.👍

**Comment by heartlog** [comment]
Hey dev ! App is great and very useful..
But some features are lacking in app. You can see features of Microsoft app, that made it for advance level.
You can check their [docs section](https://www.kok-emm.com/docs/image-detection/basic), where all features are described.
