### ISSUE TITLE
[Bug] App Rotation

### ISSUE THREAD

**Issue by dokie80** [Nain57/Smart-AutoClicker#27]
If I start the app on portrait mode, and launch other app in landscape mode, the smart autoclicker can't capture half of the screen, it's like it's still on portrait mode eventhough the UI show correctly (rotated when I switch to landscape)...
I can't even move the floating UI buttons to the right side of the screen. 

So if I want to use the smart autoclicker on landscape orientation app, I have to make sure that I launched it on landscape at the first time. 

This is problematic if the homescreen/launcher doesn't allow landscape mode.

Other than that, it works without problem on my phone (p30 pro)

Thanks

**Comment by Nain57** [comment]
Hi,

Can you specify the version of the application, as well as your Android OS version ? Thx !

**Comment by dokie80** [comment]
> Hi,
> 
> Can you specify the version of the application, as well as your Android OS version ? Thx !

Android 10
Smart Autoclicker 1.0-rc1

**Comment by Nain57** [comment]
This is an old version of the Smart AutoClicker. This should be fixed on the latest version:

* GitHub: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.0-RC4
*F-Droid: https://f-droid.org/packages/com.buzbuz.smartautoclicker

**Comment by dokie80** [comment]
> This is an old version of the Smart AutoClicker. This should be fixed on the latest version:
> 
> * GitHub: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.0-RC4
>   *F-Droid: https://f-droid.org/packages/com.buzbuz.smartautoclicker

You are right! I didn't realize there's an update. Just update and tested it... No problem with the orientation now... Sorry 🙏
Thanks! ☺
