### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by kentpachi1** [Nain57/Smart-AutoClicker#275]
1. The click coordination must be specific only
- Add an option that it will tap the exact image, there is a multiple scenario were i need to tap that moving image around.
in ahk, code is something like this "Click, %FoundX%, %FoundY% Left, 1" were it will tap/click the exact image found even if it moves around

2. the only option is screen or exact screenshot of region area search only
- Add an option were we can specify the exact region of the screen to imagesearch an image.

3. Add an option to textsearch for example, we will set a region search in the screen and if the specified text like "start" found, it will tap or do action. this is very useful especially if the text has a transparent background were exact imagesearch is useless.

**Comment by Nain57** [comment]
Not a bug
