### ISSUE TITLE
Ramdom click

### ISSUE THREAD

**Issue by NoobMan001** [Nain57/Smart-AutoClicker#28]
Randomly click on the desired area. Thanks for the development.

**Comment by TREYWANGCQU** [comment]
hello, it could be easily to add random extra time to ```mainHandler.postDelayed``` like,

```kotilin
 @WorkerThread
    private fun notifyClickDetection(click: ClickInfo) {
        isAreaFound = true

        mainHandler.post {
            detectionInfo?.second?.invoke(click)
        }

        mainHandler.postDelayed({
            isAreaFound = false
        }, click.delayAfterMs+ Random.nextLong(0,300))            /** 😏😅 */
    }
}
```
the file is named [ScreenDetector.kt](https://github.com/Nain57/Smart-AutoClicker/blob/d3073f8519b89ec87968973003b2bed26e8dde12/detection/src/main/java/com/buzbuz/smartautoclicker/detection/ScreenDetector.kt).

**Comment by Becktor** [comment]
Would also love this feature

**Comment by BenjaminWegener** [comment]
https://github.com/Nain57/Smart-AutoClicker/pull/101
