### ISSUE TITLE
Screen record softlock when creating new condition

### ISSUE THREAD

**Issue by LostLinguine** [Nain57/Smart-AutoClicker#284]
If you screen record while attempting to screenshot a condition it will softlock your device forcing you to restart the device at the lock screen to fix it.

This can be repeated by
1: opening and starting any recording app (this worked on my oneplus 8ts built in screen recorder and x recorder)
2: creating a new condition

If done correctly the menu will disappear and your screen will cease to function

Device: oneplus 8t
Android version: 11
Smart Auto Clicker version: 2.1.4

**Comment by Nain57** [comment]
Closed: Old bug format and stability have improved since. If you still have the issue, please open a new ticket.
