### ISSUE TITLE
scenarios sort by created upon import

### ISSUE THREAD

**Issue by pnkpp2** [Nain57/Smart-AutoClicker#288]
**Describe the bug**
scenarios sort by created upon import, and have to re-arrange it every import, even saving the new arrangements.

 - Smart AutoClicker v2.1.4

**Comment by Nain57** [comment]
Hi.

I don't really understand the issue here. What is incorrectly arranged ? 
The imported scenarios are not ordered by name ?
The events in an imported scenario don't keep their order ?
Same for actions ?

This is not clear. Please always provide a .zip of a scenario reproducing the issue

**Comment by pnkpp2** [comment]
Upon importing a saved scenario, it is not arranged by how you initially arranged it is sorted by time created like for example I imported 1 file, and it does 3 things click image1 then click image 2 then image 3 then I arranged it by the first command it will click is image 3 then 1 then 2 and save it, after reloading the save file scenarios the arrangement still 1>2>3 not I after I arrange it to 3>1>2.

The events in an (updated) imported scenario don't keep their order.

**Comment by Nain57** [comment]
Should be fixed in next version by 
https://github.com/Nain57/Smart-AutoClicker/commit/1c66a03635b8ad6401ac4f14b1771e65ad23cae2

Luckily, the issue was in scenario import, not in the export. So even the scenario created before this fix will be loaded with the correct order.
