### ISSUE TITLE
 It's not a mistake! I'm sorry.

### ISSUE THREAD

**Issue by AnTijojo** [Nain57/Smart-AutoClicker#289]
The first thing I'd like to tell you is that there are not enough additional settings. More hypky so that there are more options.

Example: 1
I'm playing and the character is spinning around me. It is inconvenient to make 10 sknin shots, so why not do pixel by pixel?

Example: 2
I make a screenshot of the game to enlarge the object in order to fix it and then beat or other actions, but so does not get. Bonaly the screen resolution changes.

Example: 3, 4
Let's say I play and see the inscription of the character, I fexiruyu it but the background does not allow you to beat "because it is constantly different" why not make it so that bfla function "match"? From 1% to 100%. That gives me two reasons! The inscription he sees, but you need to hit gorazhno lower and as the character rotates around us need to cardinatami it can not do. Make it necessary to hit a couple of a few pixels below. Let's say to make an arrow or something like that to be clear where he will hit when changing settings.

Thank you for reading and make a good update!

**Comment by Nain57** [comment]
Does not use bug report template
