### ISSUE TITLE
Accessing config storage location requires root

### ISSUE THREAD

**Issue by mareck8** [Nain57/Smart-AutoClicker#29]
It is not possible to access the storage location of the app without a rooted device.
No backups or modification of the config files are possible.

**Comment by norrir** [comment]
Being able to share files on non-root devices would be a great addition! 

@Nain57 I was actually looking through your post history on reddit to see if I missed it haha. I know you mentioned a different screen size means the clicks won't work post transfer. If this has any part in stopping you from adding this option, please know that it'd be much easier to reformat clicks than doing all the settings + photos all over again for the end user! Thank you for makng this amazing software.

**Comment by Nain57** [comment]
This feature have been implemented since 1.5.0.
It is now possible to export/import scenarios.
