### ISSUE TITLE
{feature request}

### ISSUE THREAD

**Issue by DhaWae** [Nain57/Smart-AutoClicker#292]
Feature 1. It would be awesome to have it so the overlay can restart itself when it crashes. I've experienced sometimes when the RAM usage becomes high the overlay can crash. Is there a way to make it restart itself?

Feature 2. Image search by PNG. It would be awesome if you were able to look for an object no matter the background as this is very hard with the current method.

**Comment by Nain57** [comment]
Not a bug.
