### ISSUE TITLE
[Feature Request] Real AI

### ISSUE THREAD

**Issue by yingshaoxo** [Nain57/Smart-AutoClicker#293]
1. Time-lapse screenshot: in some game, for example, call of duty, you can't detect running state by using screenshot unless you do delay screenshot.
2. In a period of time, if some pictures appear within 20 seconds, perform a certain operation, such as playing sound. AI is state machine, if pattern similar, they do operations. For example, in call of duty, if you have cars and teammates are out of safe area, then it is always safe to save them. If you add this feature, then the app will give user a tip: "save people now, because it is safe")

**Comment by Nain57** [comment]
Does not use bug report template
