### ISSUE TITLE
Actions don't work on BlissOS QEMU VM

### ISSUE THREAD

**Issue by maximilionus** [Nain57/Smart-AutoClicker#295]
**Describe the bug**
As the title implies, although **Conditions** works as expected, all **Actions** won't execute under the **BlissOS 14** virtual machine running on QEMU. I'm not sure if it is really related to this application, or to the system itself. If I have more free time, I will definitely try to reproduce this with **Android-x86** and **BlissOS 15** images.

**To Reproduce**
1. Create basic scenario with default settings.
2. Create the event with "Click" action on icon visible condition.
3. Start execution.

**Expected behavior**
App icon being pressed, application start.

**Detection scenario**
[SmartAutoClicker-Backup.zip](https://github.com/Nain57/Smart-AutoClicker/files/12323804/SmartAutoClicker-Backup.zip)

**Video**

https://github.com/Nain57/Smart-AutoClicker/assets/29492157/8cca843b-d62d-4e3f-9c92-b095697d94c1

**Virtual Machine:**
 - Device: **BlissOS 14.10** on **Qemu 8.0.3**
 - Android OS version: 11 _(x86_64 architecture)_
 - Smart AutoClicker version: 2.1.4

**Comment by maximilionus** [comment]
Reporting from the Bliss OS `15.8.6` _(Android 12L)_ on the same hardware - everything works fine, no issues detected. Again, not sure if it is related to the Android version or it's just the ROM-specific issue.

**Comment by Nain57** [comment]
Hi, thanks for your inputs.
I have never heard of that emulator, but this issue can come from 2 things:
* Clicks and Swipe are executed via the Android Accessibility Service, maybe there is something wrong within their OS ? This can be verified easily by installing any simple autoclicker on the Playstore and checking if it can clicks.
* Android click injection restrictions when using overlays: some platforms change chose restrictions. Generally, they don't update the overlay size correctly and keep thinking that the dialog are opens while they are not. This can be worked around by not opening the scenario configuration dialog and directly start detecting.

**Comment by maximilionus** [comment]
You were right @Nain57, turns out it was really the ROM issue. None of the several clickers I've tried work. I'm not sure what exactly is blocking input, but it's not a problem with this clicker app.

I suppose this issue can be closed as it is nothing to do with this project.

Thank you for developing such an amazing tool.
