### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by c-sanchez** [Nain57/Smart-AutoClicker#297]
Support for translations.
It would be nice to make the program translateable into other languages.
I would like to translate it into Spanish :)

**Comment by adfx** [comment]
I can help translating to german. PM me if interested.

**Comment by c-sanchez** [comment]
Hi @adfx I made a thread a while ago to help a little with the translation of Smart AutoClicker to other languages.

If you are interested you can take a look at it, I should upload the files of the latest version to the thread, but maybe it's just a matter of looking for the new files in the source code.

https://github.com/Nain57/Smart-AutoClicker/issues/322
