### ISSUE TITLE
I can not click gui

### ISSUE THREAD

**Issue by win64** [Nain57/Smart-AutoClicker#3]
Information in title.

**Comment by NguyenDuck** [comment]
You can see me for some screenshots?

**Comment by win64** [comment]
yes i see screenshots

**Comment by Nain57** [comment]
I might need more information to fix this.
You can't click GUI but which one ? The scenario list ? The floating menu ? Something in the dialogs ?

**Comment by win64** [comment]
> I might need more information to fix this.
> You can't click GUI but which one ? The scenario list ? The floating menu ? Something in the dialogs ?

I can't click to floating menu, i click and it not get reaction. if i click to it, starting app locating under it.
P. S. sorry for my english
device:honor 6A, android version:7

**Comment by islam2hamy** [comment]
Me too
Os :miui 11.0.2
Android : 7.1.2

**Comment by win64** [comment]
after all ladt updates bug is not be fixed, l hoping for fix...

**Comment by Nain57** [comment]
I can't reproduce it on any of my phones or the emulator.
By seeing your phones, this seems either related to MIUI or Android 7. I will try to investigate but this might be tricky without any way to validate it.

**Comment by k-y-a** [comment]
> 
> 
> I can't reproduce it on any of my phones or the emulator.
> By seeing your phones, this seems either related to MIUI or Android 7. I will try to investigate but this might be tricky without any way to validate it.

Reproducible to Nox Player 7.0.1.2 using Android version 7

I think same issue as #19 #20

**Comment by Nain57** [comment]
Fixed in version RC4: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.0-RC4
