### ISSUE TITLE
wiki & build guide PLEASE

### ISSUE THREAD

**Issue by TREYWANGCQU** [Nain57/Smart-AutoClicker#30]
wiki 
thanks

**Comment by Nain57** [comment]
Hi, what do you expect to be in that wiki ?

**Comment by TREYWANGCQU** [comment]
> Hi, what do you expect to be in that wiki ?

like building process, lib, et al.

**Comment by Nain57** [comment]
As the application is a standard Android app (open and click on deploy), and due to the lack of time, this won't be done.
