### ISSUE TITLE
The user guide screen supports landscape.

### ISSUE THREAD

**Issue by Jesse205** [Nain57/Smart-AutoClicker#302]
![Screenshot_20230816_214342_com.buzbuz.smartautoclicker.jpg](https://github.com/Nain57/Smart-AutoClicker/assets/51242302/31147e94-cb47-4b50-861e-de9178567411)
Some users will use this software on the tablet. Forcible vertical display is not user friendly.

**Comment by Nain57** [comment]
Supporting rotation is a tricky challenge when dealing with an Activity + Smart Autoclicker overlay & dialogs + tutorial overlay.
Development quantity and risk are not worth it, tutorials are meant to be played once for less than five minutes
