### ISSUE TITLE
Cannot interact with the phone screen when starting a scenario after 2.2.0 update

### ISSUE THREAD

**Issue by MR-KO** [Nain57/Smart-AutoClicker#306]
**Describe the bug**
Like the title says, I cannot interact with the phone screen when starting a scenario after the recent 2.2.0 update. This includes all interaction: clicking, swiping, etc. Nothing happens, it's as if I have a normal screen instead of a touch screen. I cannot swipe to get my notification center opened, I cannot swipe from the bottom to open the home menu, etc. Downgrading to 2.1.4 fixes this and returns the interaction back to normal. I read the changelog and some of the commit history of 2.2.0 (commit titles only), but could not see anything that indicated this was intended.

**To Reproduce**
1. Open Smart Autoclicker (version 2.2.0)
2. Start any scenario (I've tried all of my scenarios, even a new one, made no difference)
3. Observe that you can no longer interact with the screen yourself, only with the pause/stop/settings controls of Smart Autoclickers floating menu (and of course Smart Autoclickers actions themselves, that works just fine).

**Expected behavior**
I'd like to be able to use my phone again, so I'd like to be able to interact with my screen like normal, while Smart Autoclicker is running. 

NOTE: There is a really, really tiny window in which, after starting Smart Autoclicker, where you can interact with the screen. I estimate this to be in the order of 50-100 ms or maybe even less, as I could sometimes, barely get 1 touch in before I was locked out again. 

**Detection scenario**
N/A - any

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mix 4
 - Android OS version: Android 12 (MUI 13)
 - Smart AutoClicker version: 2.2.0 (from F-Droid)

**Comment by Mohmotte** [comment]
I have the same so I downgrade for the moment...

**Comment by wordpad25** [comment]
Was able to resolve by adding a short wait action at the start.

**Comment by Nain57** [comment]
Are you using the Debug Overlay ?
On some phones, there is an overlay security that prevent interactions if they are too big, and I wonder if that's the source of your issue.

**Comment by MR-KO** [comment]
I was not using the debug overlay, just the normal execution of a scenario (so also without reporting). Using the debug overlay never gave me any problems before (and it is/was invaluable in debugging my scenarios, great feature :pray: ) , but I did not check it this time with 2.2.0. If you want I can try it with the debug option? Though I doubt it would make much difference in behavior.

**Comment by Nain57** [comment]
No need to test with the debug overlay if the issue is already happening without it.
I'm still trying to find the root cause of the issue, as I'm unable to reproduce it on any of my devices.

If other people have this bug as well, can you share the brand/type of device you use, as well as the Android version ? This will really helpfull

**Comment by Nain57** [comment]
I think i might have been able to reproduce the issue with an emulator. This should simply fix the issue https://github.com/Nain57/Smart-AutoClicker/commit/a8527ec5a7688e8242d9eda9be09b7a35d8dce5e

If anyone with a real device with this can try this debug apk and tell me if the bug is still there ?
[smartautoclicker-fDroid-debug.zip](https://github.com/Nain57/Smart-AutoClicker/files/12640437/smartautoclicker-fDroid-debug.zip)
This apk will install alongside your Smart Autoclicker app, with a blue icon, so no need to worry about your scenarios

**Comment by MR-KO** [comment]
Hi, thanks for the quick resolution, that does indeed do the trick! I can now interact with my phone as normal, while Smart Autoclicker is running a scenario. Enabling the debug overlay still prevents me from interacting with my phone (other than with SA), but that is to be expected as that was always the case. Much appreciated! :fist_oncoming:

**Comment by Haulien** [comment]
Loving the app, but also having the same issue. Experiencing it on 2.2.0, 2.3.1, and the debug build provided above. 

I assumed it was originally my click delay (they were set to 10ms), however even setting it to 1s (1000ms), I'm still needing a dozen+ taps to activate the pause button, it's ht or miss. 

I should note I tried a few other shady-looking autoclicker apps before landing on this one, and they still allow me to interact with their on-screen controls even when doing a 10ms delay, which I find strange. 

Different device and android version from OP too:

Device: Samsung Galaxy S22 Ultra
Android OS version: Android 13 (OneUI 5.1)

**Comment by Nain57** [comment]
Closed: Old bug format and stability have improved since. If you still have the issue, please open a new ticket.
