### ISSUE TITLE
A cross instead of picture searched

### ISSUE THREAD

**Issue by Mohmotte** [Nain57/Smart-AutoClicker#307]
I have a cross instead of picture searched

![1693189282245](https://github.com/Nain57/Smart-AutoClicker/assets/71752639/dc027bce-6453-4f6a-b34d-f38a9dcd26bb)

Sorry for my poor English because I'm French

**Comment by Ahmad607h** [comment]
Thank you nain57 for the great app.

I want the square area resulting from the screenshot to be smaller than that to narrow the search field even more.  Can it be a circle and can be made smaller.  Also if you can add a search for a specific color that would be great.

Thank you very much

**Comment by Mohmotte** [comment]
Scenarios with cross can't be saved

**Comment by Nain57** [comment]
The cross is displayed because the condition image file can't be found.
If this scenario comes from an import, did you alter the zip file ?
Have you removed/changed something with the app data folder ?

**Comment by Mohmotte** [comment]
I did the scenario with the same condition and I have still a red cross... Picture finded is still here in the scenario and I see the picture crossed when I execute the scenario and it's not an import but a first creation...

**Comment by Nain57** [comment]
Is this happening to all your conditions or only a few ones ?
Is this also happening to new conditions created ? For conditions you copy ?

The red cross appears at which moment:
* when the dialog condition is opening after taking a new condition ?
* when you save the new condition and it goes back to the condition list ?
* when you save the event and open it again to check the condition list ?
* when you save the scenario and open it again to check the condition list ?


Please always follow the BugReport guidelines provided when you create a bug, i'm missing a lot of key information to investigate.

**Comment by Nain57** [comment]
Closed: Old bug format and stability have improved since. If you still have the issue, please open a new ticket.
