### ISSUE TITLE
Rearranging events really slow when many exist

### ISSUE THREAD

**Issue by wordpad25** [Nain57/Smart-AutoClicker#309]
New events are added to the bottom. 
If there are 100+ events, rearranging new event back up top is almost unfeasible as event dragging action cancels after max of one screen length. 

Event rearranging dragging action should continue scrolling up if event is dragged to the top.

**Comment by Nain57** [comment]
Fixed: Ui have been revamped. Reorder can be made with "<<" and ">>" buttons, or by clicking on the index (x/y) box the specify directly the position.
