### ISSUE TITLE
An adaptation problem of layout

### ISSUE THREAD

**Issue by yuhuitech** [Nain57/Smart-AutoClicker#31]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the permission grant page, **texts of the last line could not be seen fully**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.0-RC4, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see the text in the last line. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.add a new scenario and click it
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/129339075-2c30ffb0-bdb6-4f99-b004-db606ef28fa7.png" alt="copy" width="250"/>

**Environment**

1. Version of Smart-AutoClicker : 1.0-RC4
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by Nain57** [comment]
Thx for your input. I will take a look at this issue for the next version.

**Comment by Nain57** [comment]
Thanks for you contribution.
Your commits have been merged to master and will be part of the next version !
