### ISSUE TITLE
2.3.0 version crashes

### ISSUE THREAD

**Issue by zguinga23** [Nain57/Smart-AutoClicker#313]
I updated the app from ver 2.2.0 to 2.3.0. But this one keeps crashing. It opens for 1 or 2 seconds then crashes
 - Device: [Xiaomi Mi11 Pro]
 - Android OS version: [Android 13]
 - Smart AutoClicker version [e.g. 2.3.0]

**Comment by rizaemet** [comment]
Same here.
Xiaomi Mi 9
Android 11

**Comment by SlavaPVR** [comment]
Samsung 22

If you clear the data as a new application, it starts working. When
restoring a backup of the scripts, the application works, but not on all
pictures; some need to be updated.

ср, 20 сент. 2023 г., 22:51 Rıza Emet ***@***.***>:

**Comment by Nain57** [comment]
Just saw your messages.
I have removed the apk for now, i'm working on the issue as soon as possible.

**Comment by zguinga23** [comment]
Actually, it works after cleaning the data and cache of the previous version

**Comment by c-sanchez** [comment]
Weird, it hasn't given me any problems, although I did a clean installation of the program, not an update.
I guess what @zguinga23 says is the case.

**Comment by Nain57** [comment]
Should be fixed with 2.3.1, build is ongoing and should be available in 20 minutes.

**Comment by rizaemet** [comment]
The problem fixed with version 2.3.1. Thank you @Nain57
