### ISSUE TITLE
Dissida Opera Omnia won't accept more than 4 instances of conditions and then it immediately stops.

### ISSUE THREAD

**Issue by MidnightKun** [Nain57/Smart-AutoClicker#316]
The bug is basically this on the newest version of the app that I downloaded, I tried to automate using the quest pictures to select them and go about doing them. Unfortunately when I attempted setting up a couple of conditions with a series of taps and clicks it would only do 3 separate conditions. Since apparently I need more than one condition to get the autoclicker to do anything I want it to.

**Comment by Nain57** [comment]
Doesn't follow bug report template
