### ISSUE TITLE
Debug overlay don't click

### ISSUE THREAD

**Issue by Mohmotte** [Nain57/Smart-AutoClicker#318]
**Describe the bug**
I have two phones, on one it's click with debug overlay and an other, it isn't click with debug overlay

**To Reproduce**
Switch Debug Overlay ON

**Expected behavior**

**Smartphone (please complete the following information):**
Phone with bug
 - Device: POCO X4 Pro 5G
 - Android OS version: 12
 - Smart AutoClicker version 2.3.1
 
Phone without bug
 - Device: POCO X4 GT
 - Android OS version: 13
 - Smart AutoClicker version 2.3.1

The phone who have Android 12 update into Android 13 and the problem is solved

**Comment by Nain57** [comment]
This is a known limitation of the debug overlay.

Closed:  Feature have been reworked and user should not encounter such scenarios
