### ISSUE TITLE
When multiple events exist: An event with multiple swipe actions can only execute the first swipe

### ISSUE THREAD

**Issue by snowyu** [Nain57/Smart-AutoClicker#323]
**Describe the bug**

When there are multiple events, if one of the events contains multiple swipe actions, that event can only execute the first swipe action.

For example:

* Event 1:
  * Swipe up
  * Swipe down
* Event 2: Click close ad button if any

In this case, Event 1 will only swipe up and then get stuck there. It never goes on to execute the "swipe down" action within the same event.

This appears to be caused by the events getting reinitialized after each screen change. So Event 1 gets reset to the first swipe up, and cannot continue the sequence of swipes defined in the event.

**Expected behavior**

The multiple swipes in a single event should execute sequentially without the event getting reset.

**Comment by Nain57** [comment]
Closed: Old bug format and cannot reproduce. If you still have the issue, please create a new ticket.
