### ISSUE TITLE
Not clicking on condition 

### ISSUE THREAD

**Issue by lautit** [Nain57/Smart-AutoClicker#327]
**Describe the bug**
On the latest update, 2.3.1, the click on "Condition" is not clicking. It does work when switching to click on position.
Update: both on 2.2.0 and 2.3.0, works as expected.

**To Reproduce**
1. Set a Click event to Condition
2. Select either One or All conditions
3. Switch the Click event to Selected position
4. Select the position to the same condition

**Expected behavior**
On 2, the condition should be clicked as on 4

**Detection scenario** 
[FarmCoins.zip](https://github.com/Nain57/Smart-AutoClicker/files/12888271/FarmCoins.zip)
You can see 3 conditions, taken from versions 2.3.1, 2.3.0 and 2.2.0 respectively
The game is [Summoner's Greed](https://play.google.com/store/apps/details?id=com.pixio.google.mtd)

**Screenshots**
Click event set to Condition
![Screenshot_20231012_211358_Summoner](https://github.com/Nain57/Smart-AutoClicker/assets/14226299/b876a5e0-3ec9-45c9-b135-e4830895fe27)
Click event set to Selected position
![Screenshot_20231012_211353_Summoner](https://github.com/Nain57/Smart-AutoClicker/assets/14226299/dccf0afc-b6cc-49f7-9c77-5e5fab7b6c25)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23 Ultra
 - Android OS version: Android 13
 - Smart AutoClicker version 2.3.1

**Comment by lautit** [comment]
This unfortunately breaks every script I have made... Will try to rollback to 2.3.0 and check if it's fixed.

**Comment by cf8865042** [comment]
Struggling with the same issue. My solution is setting the conditions from 'One' to 'All' and choose one position to click on. It will works. However It would be frustrating if you have many conditions in the event. Besides, this issue only occurs on newly created event while events created before 2.3.1 works fine.

**Comment by lautit** [comment]
Found out that exports taken from 2.3.1 also remove all Click on Condition events. Maybe something related to the migration of selecting condition on All?

**Comment by tosamyng** [comment]
I have also a problem with click on condition. When I make a new event it works standalone but as soon as I disable it and only enable it from a different event toggle it can see the condition in debug mode but refuse to click it.

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

I'm struguling to understand the issue, as you seem to talk about different issues.
If there is a issue with scenario migration, please open another bug.


I can't reproduce the issue described, but i'm not sure to understand what are the steps to reproduce it.
This is what I understand:

---
## Steps:

1- Create an Event
2- Create a Condition for this Event
3- Create a Click Action for this Event and select "Condition" in the "Click on" field, then select the Condition from step 2
4- Change the Event Conditions field to One
5- Edit the Click Action for step 3 and select "Selected position" in the "Click on" field, then select a position


## Expected Behaviour:

When detecting the Condition from step 2, a click on the selected position should be executed


## Actual Behaviour:

The click is executed on the Condition 2

---
Is this correct ? I guess not because I can't reproduce it.


Note: When providing a scenario for a bug report, try to provide the smallest possible one, only with the required items to reproduce the bug. I don't have much time to work on this application and this really helps me fixing the bugs quicker

**Comment by Nain57** [comment]
For now, i can safely assure that there is no issue in:

* Click migration when transitionning from 2.2.0 to 2.3.x. Code have been reviewed and several more unit test have been added: https://github.com/Nain57/Smart-AutoClicker/commit/200bb8150d4a88374edf2d893530d58ee1536313
* Scenario import (scenario from old and current versions). Code have been reviewed and several more unit test have been added: https://github.com/Nain57/Smart-AutoClicker/commit/07de8cf71e434764ea8cabc835f8e01ee94ad56e

Note: the UI before the click on condition changes was allowing the user to define some non sense. It is no longuer the case, but if a scenario containing of those is loaded in future version, an explicit error will be shown in the scenario configuration

**Comment by lautit** [comment]
Hi Nain! Thanks a lot for reviewing this bug. I'll retest the migration and post another bug if necessary.

Regarding the Click event, the reproduction steps you suggested are not entirely correct, I would suggest trying the following:

---

*Steps:*
1- Create an Event
2- Create a Condition for this Event
3- Change the Event "Conditions" field to "One"
4- Create a Click Action for this Event and select "Condition" in the "Click on" field

Expected Behaviour:
When detecting the Condition from step 2, a click on the Condition should be executed

Actual Behaviour:
The click is not executed on the Condition from step 2

---

The Click on a Selected position is just to demonstrate that the click itself works, but not when clicking on conditions.

**Comment by lautit** [comment]
I mamaged to reproduce it by creating a Scenario on version 2.2.0 and later switching to version 2.3.1

**Scenarios**
![Test_Click_YouTubeShorts.zip](https://github.com/Nain57/Smart-AutoClicker/files/13198032/Test_Click_YouTubeShorts.zip)

_Report on Scenario created using version 2.2.0 and running it with version 2.2.0_
![Screenshot_20231029_092344_YouTube.jpg](https://github.com/Nain57/Smart-AutoClicker/assets/14226299/4ab10840-69ae-48a9-a92b-7e21e98c8504)

_Report on Scenario created using version 2.2.0 and running it with version 2.3.1_
![Screenshot_20231029_092500_YouTube.jpg](https://github.com/Nain57/Smart-AutoClicker/assets/14226299/7ec0f40d-815c-43b6-8e72-d13d826c6953)

_Report on Scenario created using version 2.3.0 and running it with version 2.3.1_
![Screenshot_20231029_092625_YouTube.jpg](https://github.com/Nain57/Smart-AutoClicker/assets/14226299/e16ea170-998e-40b8-adeb-4fe8494b727d)

**Comment by Nain57** [comment]
Thanks for your clarifications.

For the steps specified in your first post, I have followed them but i still can't reproduce the issue. When you use the debug overlay, can you see the condition actually detected ? Also; is your condition newly created or is a condition copied from previous versions ? 

With the version 2.3.0, I have vastly changed the way the detection was done (release note [here](https://github.com/Nain57/Smart-AutoClicker/releases/tag/2.3.0)). It is way more precise and faster than before, but the optimal parameters have changed. There is an auto migration handling most of the cases but unfortunately, you might need to change manually your conditions for a few corner cases.

For your second post, this illustrate what i just explained, your 2.2.0 condition is never detected on 2.3.0, but simply recreating it should fix the issue.

Unfortunately, I don't think there is a lot i can do for that.

**Comment by lautit** [comment]
It's totally understandable. I have tuned a couple of settings here and there, while refining some of the scripts, and haven't found any issues so far. I think we can close the bug. Thanks again for the detailed explanation and maintenance of the app!

**Comment by lautit** [comment]
I think we can close the bug
