### ISSUE TITLE
Is there a way this could close ads by itself? 

### ISSUE THREAD

**Issue by FeynmanVirus** [Nain57/Smart-AutoClicker#328]
A big use case of this project is to automate games, and you can gain a lot of rewards for watching ads, but a big issue which I'm facing is there are many types of 'X' buttons to close the ads.

I've tried including them as a condition but it always messes up if the background is a slightly different color...also there's no way to import pngs into the app and the in-app 'screenshotter'  cant go smaller so it captures other details as well which makes it harder for the algo. Sorry if this is a stupid ask haha.

**Comment by Bramerr** [comment]
You could try to click on skip/close location instead, all ads (for me) always have their skip/close buttons in the same place. Try it: after clicking ad, wait 60 seconds and click, the after 10 seconds click again.

**Comment by DaMaddCyantist** [comment]
> A big use case of this project is to automate games, and you can gain a lot of rewards for watching ads

Check out my click patterns here [on my GitHub](https://github.com/Neighborhood-Data-Science/instant-beer-money/tree/main/AutoClick%20Patterns). Idle Furry, for example, lets you progress by watching ads. So, I have a pattern than watches and closes the ads itself.

> a big issue which I'm facing is there are many types of 'X' buttons to close the ads...
> I've tried including them as a condition but it always messes up if the background is a slightly different color

Try detecting the image on the 'screen' vs 'exact' location. Also try increasing the detection threshold between 15% and 20%. This works for me and closes 95% of ads no problem When it doesn't close one, I add the new close-icon to the condition so that it can find it in the future.

> the in-app 'screenshotter' cant go smaller so it captures other details as well which makes it harder for the algo

Try zooming in (using two-fingers) on your phone when you are prompted to take a screenshot. That will allow you to capture more details.

**Comment by Tminus73** [comment]
Not sure if the above post answered or helped you in your automation of closing ads but the game I run the auto clicker for ad watching gives the reward once you've watched the ad on 95% of the ads so I set up a swipe function to exit the application after 1 minute of the ad starting, then just reopen the app and re watch.

**Comment by DaMaddCyantist** [comment]
> I find this alot easier than adding images for every ad because they will always be new ads or ads that have the >> arrows instead of the X

This is excellent insight. I began thinking of another way to do this as well because new ads are always popping up.
I like the timer option as a fallback. Thanks!

**Comment by FeynmanVirus** [comment]
> Not sure if the above post answered or helped you in your automation of closing ads but the game I run the auto clicker for ad watching gives the reward once you've watched the ad on 95% of the ads so I set up a swipe function to exit the application after 1 minute of the ad starting, then just reopen the app and re watch. I find this alot easier than adding images for every ad because they will always be new ads or ads that have the >> arrows instead of the X

Thank you for this! This resolves all of the issues and works like a charm. I can now leave my phone on automation all night without worrying about it getting stuck on a particular type of ad :)
