### ISSUE TITLE
More features should be added to app.

### ISSUE THREAD

**Issue by fukudck** [Nain57/Smart-AutoClicker#34]
Smart-Autoclicker is really good and easy-to-use, but i think you should add the following features.

 1.  Show image conditions location.
 2.  Multiple Click
 3.  Smaller Image Condition

Image conditions capture still has bug. The selector is often skewed when on landscape screen.
Hope you will add these features soon.
Device info:
App version: 1.1.0 from github
Android 9
Full HD screen
(My English is really bad, hope you understand it)

**Comment by Nain57** [comment]
Enhancement implemented in v1.2.0 available here: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.2.0 or on F-Droid within a few days.
