### ISSUE TITLE
[Feature Request] Allow to hide menu on screen display

### ISSUE THREAD

**Issue by l2eused** [Nain57/Smart-AutoClicker#343]
Please add option to hide **menu** on screen display and using notification to interact instend (start, stop, settings, etc)

Why I want this feature:

- to aviod screen burn when using app in long time (with same position it can be easier to get burn)

- to prevent condition not detect when **menu** is display above condition (it might be bugs but I think it because this app using screen capture... and yes **menu** can be capture by app too)

**Comment by Shadow-Hunt3r** [comment]
Yea, it would be nice to have a way for the smart autoclicker to be able to remove it, and possibly view the screen with the screen turned off maybe using something similar to some scrcpy tools which utilize ADB for such a task

This could very much be handy if anyone ever needs to leave the autoclicker running for some specific task overnight and doesn't wish to risk screen burnin
