### ISSUE TITLE
Suggestion: Text Recognition

### ISSUE THREAD

**Issue by BeepaBoop** [Nain57/Smart-AutoClicker#36]
I play a game that has captchas in the form of numbers scrambled on a key pad each time a new one pops up and text recognition would help make it so much easier for me instead of me having to do it every time.

**Comment by Nain57** [comment]
Text Recognition is way above this application capabilities, it would requires to switch to OpenCv instead of my manual recognition.
Maybe once all of my top priorities have been implemented.

But thanks for your suggestion !
