### ISSUE TITLE
Samsung Z Fold doesn't do right screen 

### ISSUE THREAD

**Issue by MrCavey** [Nain57/Smart-AutoClicker#360]
**Describe the bug**
So this used to work. Haven't used it in while but when i open the phone up it no longer allows me to do anything on the right side. Can't move the widget or do captures. 

**To Reproduce**
1. Open phone
2. Try to move or detect anything on the right side 

**Expected behavior**
Able to do stuff on right side 

**Detection scenario**
Shouldn't be needed 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Z Fold 4
 - Android OS version: 13
 - Smart AutoClicker version 2.4.1

**Comment by Nain57** [comment]
Closed: Old format. If you still encounter the issue, please open a new ticket with the new provided format.
