### ISSUE TITLE
Rotation makes the app stop working

### ISSUE THREAD

**Issue by DatPenguin** [Nain57/Smart-AutoClicker#361]
Hi,
I have been using this autoclicker for a few months now, and since some versions I encounter this bug.

I start the Smart Autoclicker, run my scenario and an authorization popup appears to allow the app to record my screen. I allow it, and I can see it is working because the overlay shows a pause button. At the same time, the autoclicker reduces and I only get to see the overlay. All of this is done in portrait mode (I tried doing it in landscape, but since the autoclicker reduces, I always get back to my launcher which is only in portrait).

I then run the game I want to use the autoclicker in, which is only in landscape mode. My screen rotates, and at the moment it does, the autoclicker stops, the overlay shows the play and stop button along with the settings and the arrows ones, but the play button is grayed out.

A few versions ago, after rotating, I would get another popup asking me for permissions to record my screen (I would see it every time the screen rotated), but now I only see it once at the beginning, and never after that.

I believe the app does not request again the permission to record to Android after the rotation, thus it cannot record the screen and bugs out.

I am using a Pixel 6 on Android 14.

P.S.: Merci pour ton appli, c'est le meilleur autocliqueur que j'aie pu trouver !

**Comment by helloyanis** [comment]
I am also having this issue, here is a video of it.
Please forgive me for the discord notification sounds in it.

https://github.com/Nain57/Smart-AutoClicker/assets/40769776/b4dcd764-3bc1-4e84-9b01-c7386e80b456

Also in this state, trying to open settings and add a screenshot conditional will softlock your phone so don't do that I guess lol
A workaround I found is to quickly switch to a landscape app once the autoclicker has started.

**Comment by Nain57** [comment]
Issue is the same as: https://github.com/Nain57/Smart-AutoClicker/issues/338
This has been identified and a fix is currently being tested.
