### ISSUE TITLE
Prolonged use causes the Smart Clicker to clash

### ISSUE THREAD

**Issue by LarchyEverything** [Nain57/Smart-AutoClicker#364]
I usually leave it on for hours or days at a time, don't ask why. But Before some recent updates, the Smart autoclicker didn't crash at all with prolonged use, now it does.

**To Reproduce**
1. Make some layout
2. use it
3. smart auto clicker will just disappear

**Expected behavior**
It doesn't tun itself off.

**Detection scenario**
[SmartAutoClicker-Backup (1).zip](https://github.com/Nain57/Smart-AutoClicker/files/13838664/SmartAutoClicker-Backup.1.zip)
)
[SmartAutoClicker-Backup.zip](https://github.com/Nain57/Smart-AutoClicker/files/13838665/SmartAutoClicker-Backup.zip)

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Moto e6 (XT2005DL), Orbic RC555L
 - Android OS version: 9, 7.1.2
 - Smart AutoClicker version: 2.4.0 and 2.4.1
 (I have two phones, moto has android 9, version 2.4.0, and orbic has android 7.1.2, and version 2.4.1

**Comment by ngethe** [comment]
same exprience

**Comment by Nain57** [comment]
Closed: Old format and stability have been improved since. If you still have issue, please open a new ticket.
