### ISSUE TITLE
[BUG] constant freeze & request permission 

### ISSUE THREAD

**Issue by Tminus73** [Nain57/Smart-AutoClicker#366]
Not sure if both issues are linked together but the first issue is that I need to request permission for accessibility all the time, not sure exactly what triggers it to 'malfunction' but that's the error I see on accessibility menu
![IMG_20240109_144122](https://github.com/Nain57/Smart-AutoClicker/assets/150806840/6cc1ec73-f2b3-47ab-93c6-24f5ed735845)

Second issue is the scenario I am trying to run keeps freezing about 90%of the time after I press the play button it will do the first event within the scenario and then freeze, I am unable to pause the scenario and have to switch back to Smart Auto Clicker application and restart the scenario to get rid of the overlay.
![IMG_20240109_144734](https://github.com/Nain57/Smart-AutoClicker/assets/150806840/d920f579-b7f8-47d2-8aca-79c528ad5426)

I have tried to generate a bug report from within the application but since the application freezes and when I switch back to the Smart Autoclicker application the bug report has not generated.

**Smartphone (please complete the following information):**
 - Device: Poco X3 Pro
 - Android OS version: android 12 SKQ1.211006.001
 - Smart AutoClicker version 2.4.1

**Comment by Nain57** [comment]
Closed: Old format. If you still have the issue, please re-open a ticket.
