### ISSUE TITLE
When system animations are disabled paused scenario can't be edited

### ISSUE THREAD

**Issue by zakius** [Nain57/Smart-AutoClicker#367]
**Describe the bug**
Disabling system animations causes the overlay to differ, the most notable difference being lack of cogwheel when you pause a running scenario

**To Reproduce**
1. Go to device settings, some devices allow you to disable animations easily, other require developer settings
2. Launch a scenario
3. Start the scenario
4. Pause the scenario 

**Expected behavior**
Overlay controls should be the same

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Zenfone 10
 - Android OS version: Android 14
 - Smart AutoClicker version: 2.4.1

overall it looks like the overlay can't be properly resized when animations are off causing it to be limited to 2 entries once you start the scenario

**Comment by Nain57** [comment]
Closed: Old format. Recreated here: https://github.com/Nain57/Smart-AutoClicker/issues/480
