### ISSUE TITLE
Multiple point swipes

### ISSUE THREAD

**Issue by glowseeker** [Nain57/Smart-AutoClicker#371]
Would absolutely love a feature where swipes can have multiple nodes, so like it swipes from 1 to 2 to 3 without "lifting" the finger in continuous motion

I'm aware that for most scenarios just multiple one-directional swipes chained together replicate it, but I'm asking for the distinct continuous part of the scenario above

**Comment by Andoroido** [comment]
Hello,

Was looking for this feature too. 

Is it implemented yet?
