### ISSUE TITLE
Scenario can't be edited after running

### ISSUE THREAD

**Issue by 19ChuAnh13** [Nain57/Smart-AutoClicker#378]
This bug is described as video shown below

https://github.com/Nain57/Smart-AutoClicker/assets/95576394/f6defbde-86f7-48f3-8515-8d10604c95ae

**Comment by Cyber5imon** [comment]
Please fix soon. Thanks!

**Comment by empjustine** [comment]
As a temporary workaround, pausing the scenario, then using the notification "show/hide" option twice fixes the "overlay toolbar" state and allows you to edit the scenario.

**Comment by jrmstuff** [comment]
Same bug still exists in 3.0.1 as is shown in the video. 

I haven't been able to figure out the temporary workaround described above.

**Comment by jrmstuff** [comment]
Bug #367 is the same topic. It is appears when system animations are disabled. Re-enabling system animations on my phone fixed the problem.

**Comment by Nain57** [comment]
Closed: old format. New bug have been created for this: https://github.com/Nain57/Smart-AutoClicker/issues/480
