### ISSUE TITLE
[REQUEST] Condition Priority

### ISSUE THREAD

**Issue by Drian2024** [Nain57/Smart-AutoClicker#382]
Condition priority or something like that the top of the condition is the main priority. For instance, the condition are finding the image of dog>cat>cow>pig. It would be nice if there will be an feature in which dog is the first thing to be recognize first, if the dog is not there, then cat and so on. The app does somehow works in which it recognizes dog, and sometimes it recognizes the other condition first.

**Comment by Nain57** [comment]
Events are already prioritized, so if you create one condition per event and order the events correctly, it will work.
