### ISSUE TITLE
[REQUEST] Increase press/swipe time limit to a longer period

### ISSUE THREAD

**Issue by locketl1te** [Nain57/Smart-AutoClicker#383]
Having the option to hold down the screen longer would be helpful for applications like wiggling a joystick in one direction or just having a button pressed down for longer than 9 seconds. After some searching it really doesn't seem like this is an option in basically any autoclicker out there.

**Comment by Nain57** [comment]
Unfortunately, that's an Android limitation, anything longer than 59s (59000 ms) will crash.
