### ISSUE TITLE
[Game changer changes] Automatically collect user interactions and now imitate them.

### ISSUE THREAD

**Issue by Tanzin01** [Nain57/Smart-AutoClicker#384]
As title says.
For click, Swipe and the time gap. Could really be a revolutionary step.

Or perhaps, instead of Jason, use text based instruction. One per line. On every 4line a gap line. Also a comment systemThis will make automatic click easier by whole lot. Since user will be able to copy paste. 

currently for big stuff, it's hard to keep track.

**Comment by Deeptanil** [comment]
Yes this makes it so much easier to use... Such as in the app 'clickmate' but theres no image detection there.

**Comment by Tanzin01** [comment]
Thank you. Now i can see there are tons of apps like this! 
Bad search engines. They didnt showed me them up unitll now if i remeber correctly. 

By chance i came across auto clicker in fdroid store, Anywah, it woukd be cool to have auto clciker itself automated!
