### ISSUE TITLE
 Suggestion: Progressive Macros and Automatic Screenshotting

### ISSUE THREAD

**Issue by brigs111** [Nain57/Smart-AutoClicker#39]
Hello, love this app.

There are times when I'll go back to a certain screen several times and want to do something different. It would be great if there was a function to progress through each macro in order and disable the previous ones.

There are also times when I accidentally interact with the screen when in the mode to capture a conditional and have to go through the process again to get that specific screen back. An option to automatically screenshot the screen as soon as you press the + button for a new conditional would be wonderful.

Thank you.

**Comment by Nain57** [comment]
Hi,

* "It would be great if there was a function to progress through each macro in order and disable the previous ones.": This is scheduled for a future version. For now, in the 1.1.1 version (to be released soon), you will be able to stop the scenario after X execution of a specific clic. More options for end control will come.

* " An option to automatically screenshot the screen as soon as you press the + button for a new conditional would be wonderful.": Are you using the 1.1 version ? I have changed to screen capture UI, allowing to first press on the overlay menu button to capture to whole screen, then use the selector to capture the wanted area of the screen.
