### ISSUE TITLE
[REQUEST] Make click on condition anti-cheat

### ISSUE THREAD

**Issue by Tenarien** [Nain57/Smart-AutoClicker#392]
As of now anti-cheat option only works with simple clicks and swipes we also need them in condition clicks and swipes I don't know why it wasn't implemented before simple oversight. We should also be able to decide by how many % the click should drift away from the detection position.

**Comment by Nain57** [comment]
Randomization is implemented the same way for all actions:
https://github.com/Nain57/Smart-AutoClicker/blob/master/core/processing/src/main/java/com/buzbuz/smartautoclicker/core/processing/data/processor/ActionExecutor.kt

It is really dumb to accuse someone on a open source code.

=> Banned
