### ISSUE TITLE
No cog options icon or arrow movement option after pausing macro

### ISSUE THREAD

**Issue by millertrial9** [Nain57/Smart-AutoClicker#393]
On one of my phones using the latest version of Smart Auto clicker there has been this issue of once I start the macro and then click pause instead of showing all 4 icons the 1 arrow to play 2 the square stop button 3 the cog icon for options and adding scenarios and 4 the four arrow icon for movement. Instead of showing all 4 it only shows the first 2 the play and stop button. So I always have to totally close the macro and restart the app totally. How do I fix this ?

**Comment by Nain57** [comment]
Closed: Old bug format and issue difficult to understand. If you still encounter this issue, open a new Bug ticket and try to illustrate your issue with screenshots
