### ISSUE TITLE
The minimum screenshot area is still too large! Wish it could support smaller area sizes! 最小截图区域还是太大了！希望能支持更小的面积大小！

### ISSUE THREAD

**Issue by iAngelovery** [Nain57/Smart-AutoClicker#394]
最小截图区域还是太大了！
部分游戏里，软件截图识别还是比需要识别的内容大得多，导致不能正确识别出位置和图片，如果容差调整的比较大，又会错误的点击其他位置。
希望能支持更小的面积大小！

————————————————

The following is from translation software

The minimum screenshot area is still too large!
In some games, the software screenshot recognition is still much larger than what needs to be recognized, resulting in not recognizing the location and picture correctly, and then incorrectly clicking on other locations if the tolerance is adjusted more.
Wish it could support smaller area sizes!

**Comment by Nain57** [comment]
Minimal size is close to the pixel, we can't zoom more.
As indicated by the tooltip, you can pinch to zoom
