### ISSUE TITLE
[REQ] Root Support

### ISSUE THREAD

**Issue by hamzaharoon1314** [Nain57/Smart-AutoClicker#401]
**Request**
Is it possible to add the Root support so you don't have to permit accessibility when you have a rooted phone?
Thanks

**Comment by Cyber5imon** [comment]
Bump... This should be pretty easy as long as you have a rooted environment to develop/test in.

**Comment by Nain57** [comment]
Closed: not a bug but more a feature request. If you think this is relevant, please create a new Feature Request ticket.
