### ISSUE TITLE
Is it possible to add simultaneous click behavior?

### ISSUE THREAD

**Issue by CN-148** [Nain57/Smart-AutoClicker#404]
For example: click two locations on the screen at the same time, or click at least two points at the same time (you can edit multiple simultaneous clicks, such as 2, 3, 4.

**Comment by plastikhub** [comment]
I did a little testing and it looks like the closest you can get to this is after setting your Conditions (screenshots, etc.) on the Actions tab of your Event, set multiple click actions that have really low press duration timings. So, I guess the answer is no or at least I haven't found a way to do it.

**Comment by aroguecoder** [comment]
bumping for multiclick feature.

**Comment by Cyber5imon** [comment]
Merge with #427
