### ISSUE TITLE
Smart Auto Clicker Randomly Closes on Nox Player Emulator

### ISSUE THREAD

**Issue by millertrial9** [Nain57/Smart-AutoClicker#405]
Recently I started using Nox Player again (latest version) and I have noticed that Smart Auto Clicker is randomly closing on the emulator. Which is odd because on all the other PC android emulators I have never had this issue I can run the auto clicker forever. What I have noticed is that usually the auto clicker does not close for a few hours, but has in moments randomly closed within minutes. Also something that I noticed which may or may not be an issue is i'm utilizing the built in macro recording for Nox player which i do with all the other emulator no problem with auto clicker. But i'm not sure that I have ever seen the auto clicker randomly close on nox player when i'm not using the build in macro recorder at the same time. Not sure there is any connection, just thought Id mention that.

**Comment by ngethe** [comment]
following have the same issue

**Comment by DopeyDopado** [comment]
> Recently I started using Nox Player again (latest version) and I have noticed that Smart Auto Clicker is randomly closing on the emulator. Which is odd because on all the other PC android emulators I have never had this issue I can run the auto clicker forever. What I have noticed is that usually the auto clicker does not close for a few hours, but has in moments randomly closed within minutes. Also something that I noticed which may or may not be an issue is i'm utilizing the built in macro recording for Nox player which i do with all the other emulator no problem with auto clicker. But i'm not sure that I have ever seen the auto clicker randomly close on nox player when i'm not using the build in macro recorder at the same time. Not sure there is any connection, just thought Id mention that.

Just check the emulator resolution and DPI setup, there are a minimum resolution and DPI accepted, check CPU cores and memory setted up too.

**Comment by Cyber5imon** [comment]
Please try using the latest [Beta 3.00v4](https://github.com/Nain57/Smart-AutoClicker/releases/tag/3.0.0-beta04) version.

**Comment by Nain57** [comment]
Closed: old issue format. If this still happen on current versions, please open a new ticket.
