### ISSUE TITLE
Function to rearrange conditions

### ISSUE THREAD

**Issue by pyjserv** [Nain57/Smart-AutoClicker#408]
Hello, I think the matching order of the action of condition-clicking depends on the arrangement order of conditions. Therefore, if the smart autoclicker can rearrange conditions, it will be more convenient to manage the events of a scenario.

For example, consider a simple scenario with three actions: click bag, click scroll, and click read. We usually capture images in the same order. However, in this order the read condition will be never triggered. If the conditions can be customly rearranged to click read, click scroll, click bag, there is only one event to handle this circumstance.

![_1713411863369](https://github.com/Nain57/Smart-AutoClicker/assets/97389952/230d3676-505e-47e2-b04c-f51d32d3b5ce)

**Comment by pyjserv** [comment]
![_1713411863369](https://github.com/Nain57/Smart-AutoClicker/assets/97389952/6cde3583-11eb-43f8-8205-a78528e92bda)

**Comment by Cyber5imon** [comment]
It would be very helpful to allow rearranging conditions.

Currenty, I have to create different priority scenarios containing the conditions I want checked first, second, etc...
