### ISSUE TITLE
Application crash randomly after a while

### ISSUE THREAD

**Issue by deepblue96** [Nain57/Smart-AutoClicker#413]
**Describe the bug**
The Application crashes randomly after running for a while

**To Reproduce**
Create a new smartdetection event with at least 2 event and image detection, add a button click event of 100ms and a delay 1second before and after the click.
run the task ensuring it find something to click and after a while it crashes.

**Expected behavior**
It should keep running.

Log attached: 
[SmartAutoclickerCrashLogcat.txt](https://github.com/Nain57/Smart-AutoClicker/files/15172604/SmartAutoclickerCrashLogcat.txt)

**Smartphone (please complete the following information):**
 - Device: xiaomi red mi note 7 (also reproduced in 3 different emulators with android 10 and 13)
 - Android OS version: 10
 - Smart AutoClicker version: current

**Comment by ngethe** [comment]
exprenced the same any update ?

**Comment by deepblue96** [comment]
the issue has NOT been fixed even at commit: 07a8d39

**Comment by deepblue96** [comment]
I cannot send it right now, but i can tell you that after 15 minutes max of the app running and looking for matches of images (at least 2 conditions) it crashes.
Yeah i know i hoped that your git was ahead and so i tried it still the same behavior.
Btw I paid for it before i knew it was broken because the ease of use was excelent, with this problem fixed it will become a great app 👍

**Comment by Nain57** [comment]
Can you try with this test apk if you can reproduce the issue?
Do not use any of the new Trigger Event features as they are not tested and might interfere with the test.

[smartautoclicker-fDroid-debug.zip](https://github.com/Nain57/Smart-AutoClicker/files/15233561/smartautoclicker-fDroid-debug.zip)

**Comment by deepblue96** [comment]
It still crashes after 10-12 minutes here is the macro:
![image](https://github.com/Nain57/Smart-AutoClicker/assets/4752625/f9cdbfd6-4dab-4ac4-8a83-faf8b587d176)
![image](https://github.com/Nain57/Smart-AutoClicker/assets/4752625/9343a279-c8fb-4e83-b37d-76ca9c465ef6)
![image](https://github.com/Nain57/Smart-AutoClicker/assets/4752625/2cb90375-9fc5-4951-b39a-2d245f958f59)
![image](https://github.com/Nain57/Smart-AutoClicker/assets/4752625/da594e2f-d99f-4105-b7ed-59b5405393ae)
![image](https://github.com/Nain57/Smart-AutoClicker/assets/4752625/a2d411fb-b20e-4167-9a99-16ffcb8b0c0c)
![image](https://github.com/Nain57/Smart-AutoClicker/assets/4752625/e7466a69-618b-440d-8cca-77c7890d08f6)
Test app chrome:
![image](https://github.com/Nain57/Smart-AutoClicker/assets/4752625/9bb58f37-b14a-4ae3-b972-d99e2886544f)

**Comment by deepblue96** [comment]
Logs:
| Header |
|--------|
| 2024-05-07 11:49:08.686  1901-4670  EGL_emulation           com.buzbuz.smartautoclicker.debug    D  app_time_stats: avg=1499.77ms min=1499.77ms max=1499.77ms count=1
2024-05-07 11:49:17.419  1901-4670  EGL_emulation           com.buzbuz.smartautoclicker.debug    D  app_time_stats: avg=8732.44ms min=8732.44ms max=8732.44ms count=1
2024-05-07 11:49:18.920  1901-4670  EGL_emulation           com.buzbuz.smartautoclicker.debug    D  app_time_stats: avg=1500.88ms min=1500.88ms max=1500.88ms count=1
2024-05-07 11:49:29.896  1901-2423  Detector                com.buzbuz.smartautoclicker.debug    E  ROI is invalid, 212/726  87/  90 in  3025/  3125
2024-05-07 11:49:29.905  1901-2423  Detector                com.buzbuz.smartautoclicker.debug    E  ROI is invalid, 436/299  87/  90 in  3025/  3125
2024-05-07 11:49:42.738  1901-2423  Detector                com.buzbuz.smartautoclicker.debug    E  ROI is invalid, 212/726  87/  90 in  3025/  3125
2024-05-07 11:49:42.761  1901-2423  Detector                com.buzbuz.smartautoclicker.debug    E  ROI is invalid, 436/299  87/  90 in  3025/  3125
2024-05-07 11:50:02.366  1901-2423  Detector                com.buzbuz.smartautoclicker.debug    E  ROI is invalid, 212/726  87/  90 in  3025/  3125
2024-05-07 11:50:02.393  1901-2423  Detector                com.buzbuz.smartautoclicker.debug    E  ROI is invalid, 436/299  87/  90 in  3025/  3125
---------------------------- PROCESS ENDED (1901) for package com.buzbuz.smartautoclicker.debug ----------------------------
---------------------------- PROCESS STARTED (5413) for package com.buzbuz.smartautoclicker.debug ----------------------------
2024-05-07 11:50:57.870  5413-5525  QualityManager          com.buzbuz.smartautoclicker.debug    I  Smart AutoClicker has crashed during it's last session !|

**Comment by Nain57** [comment]
Is this test made with the provided apk ?

This invalid ROI is related to the scenario configuration, once again i can't reproduce it as long as you don't provide me your scenario-backup zip file.

The latest log is printed by Smart autoclicker but is irrelevant when using it in a non production use case like you (service should not be stopped, here its the case because . In your first complete log, there is no trace of crash of the app, only an out of memory issue that can be explained by an invalid compilation setup.

**Comment by deepblue96** [comment]
[SmartAutoClicker-Backup.zip](https://github.com/Nain57/Smart-AutoClicker/files/15235218/SmartAutoClicker-Backup.zip)
yes the test was made with the provided apk, but it doesn't matter the scenario or the images it works great then after 10 min it crashes for no reason on both emulators and xiaomi devices

**Comment by Cyber5imon** [comment]
Please try using the latest [3.00v4 Beta version](https://github.com/Nain57/Smart-AutoClicker/releases/tag/3.0.0-beta04)

**Comment by Nain57** [comment]
Closed: old issue format. If this still happen on current versions, please open a new ticket.
