### ISSUE TITLE
toggle bug

### ISSUE THREAD

**Issue by LostLinguine** [Nain57/Smart-AutoClicker#422]
### Version of Smart AutoClicker

3.0.0-beta01

### Device brand and model

oneplus 8t

### Version of your Android OS

11

### Type

Smart scenario

### Describe what happened?

Scrolling messes with what events are being enabled/disabled so if you have a lot of events like me then this will happen and make setting up practically impossible

Uploading XRecorder_19052024_122009.mp4…

### Describe what should have happened?

Shouldnt be doing that obviously but idk if its because of all tge events i have or not, havent tested it on a new scenario.

**Comment by LostLinguine** [comment]
https://github.com/Nain57/Smart-AutoClicker/assets/125235925/507d3a7c-16a8-4cb0-aab0-fcaccc5df369

**Comment by Nain57** [comment]
Thank you for your feedback.
This is indeed a bug and it will be fixed in the next beta version

**Comment by Nain57** [comment]
Fixed in 3.0.0-beta02: https://github.com/Nain57/Smart-AutoClicker/releases/tag/3.0.0-beta02
