### ISSUE TITLE
Full screen image recognition 

### ISSUE THREAD

**Issue by DopeyDopado** [Nain57/Smart-AutoClicker#425]
### Version of Smart AutoClicker

2.4.2

### Device brand and model

Any device

### Version of your Android OS

13-14

### Type

Smart scenario

### Describe what happened?

I figured out the full screen image search lost the information on the middle to the button off the screen area so is need to setup the specific area to search that image... Don't have troubles finding the same image on the middle to top of the screen.

### Describe what should have happened?

Somewhere on the code of the fullscreen image detect have a weird bug...

**Comment by Cyber5imon** [comment]
Please provide images with examples to help understand your problem better

**Comment by Nain57** [comment]
Closed: impossible to reproduce, no update from reporter.
