### ISSUE TITLE
App almost softlocked my phone

### ISSUE THREAD

**Issue by sheesh3178** [Nain57/Smart-AutoClicker#428]
### Version of Smart AutoClicker

2.4.2

### Device brand and model

Realme C51

### Version of your Android OS

13

### Type

Dumb scenario

### Describe what happened?

- installed and open the app
- clicked +
- chose "simple" clicks and saved
- clicked the play icon
- throws me out of the app
- floating thing pops up
- clicked the third button (the one with two x and an arrow-looking thingy in the middle)
- suddenly, every part of my screen is unclickable now
- thankfully, the floating thingy is clickable
- proceed to setup the autoclicker
-  clicked the + to make a task
- chose "swipe"
- assigned clicks on screen
- assigned "repeat count" to infinite
-  played the autoclicker
- it works
- i discover something
- every part of screen is unclickable, even the floating thingy, so there's no way for me to pause it
- no clicks/action work on screen
-  decided to turn off screen with power button
- it works
- still can't click on lockscreen
- no way to escape lockscreen except fingerprint
- it works
- everything still unclickable
- think of restarting phone
- bring up power menu with volume up and power button
- cant choose restart or anything because i cant click anywhere
- discover there's no way to fix phone because the app won't crash itself even in lockscreen, and my usb debugging is turned off
- realized im effed
- "Is this a virus? But I downloaded this on F-Droid..." I said to myself
- start to panic
- tears drop
- "This is a newly bought phone, how could this happen?" I mumbled to myself as I slowly lose hope
- 10 minutes pass
- finally accept my and my phone's fate
- "There's nothing we can do."
- turn off phone
- aftter 3 minutes, noticed the app shat itself and now I can click!1!1!1!11!!!1
- "Guess I should just scroll on TikTok like a normal human-being instead of being a lazy-a$$" I said to myself happily

No seriously, this is a massive bug. I apologize for the insanely long text, but I feel like there's no better and shorter way to explain it than this.

Unless you're no tech-savvy (which I am not), you're not gonna find a way fo fix this. Thankfully, the app stopped somehow that's why I can use it now to report on Github.

### Describe what should have happened?

When I execute the autoclicker, I should still be able to click my screen. Heck, even the floating thing is unclickable once you execute it, and it only makes it more problematic if you set the "Repeat Count" to infinite, because there's basically no way the app kills itself.

**Comment by Nain57** [comment]
Hi,

You are clicking too quickly on your screen with the autoclicker, leading to this touch screen blocking. This can happen with any Autoclicker.

There is a popup explaining this at first launch of a scenario, and it can be stopped at anytime with the volume down key.
