### ISSUE TITLE
do you have paln it work on app to prevents capture?

### ISSUE THREAD

**Issue by myusernameisle** [Nain57/Smart-AutoClicker#429]
### Describe the feature

I'm using this app very well, but the smart version is not.
Since the app I'm using is an app that prevents capture, I can't actually use the smart version, but I'm only using the regular version.
So is it possible to use it on an application that prevents capture, or is there a plan to add a pause function if you click or swipe something?

### Describe the usage

I don't know exactly usage, but Some apps don't allow capture. It would be nice to add the ability to pause when it can work on those apps or clicks or swipes work on them.

### Is it a duplicate?

- [X] There is no duplicates

**Comment by Cyber5imon** [comment]
The smart verison will only work on apps that allow screen capture since it must capture the screen to recognize a section and act upon it.

Maybe if your device is rooted, you could  re-enable screen capture for the app preventing it.

**Comment by Nain57** [comment]
Smart scenario requires capture and can't work without it. Simple scenario will still work.
There is nothing I can do to remove this limitation unfortunately.
