### ISSUE TITLE
Feature request: Allow users to change default value of "delay before next click"

### ISSUE THREAD

**Issue by sudomain** [Nain57/Smart-AutoClicker#43]
I would like the ability to change the default delay of 50 (milliseconds?) between clicks. To avoid ambiguity - I know the delay itself can be changed, but I'd like to adjust the default value that shows when making a new click.

**Comment by Nain57** [comment]
Feature implemented on last version: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.2.0
The application will now remember your last value and use it as the default one for the next creation.

It should be available on F-Droid soon.

**Comment by sudomain** [comment]
Thank you! Got the update today
