### ISSUE TITLE
Add NOT operator

### ISSUE THREAD

**Issue by vindaruck** [Nain57/Smart-AutoClicker#435]
### Describe the feature

In addition of OR, AND operators, it will be great to have a NOT operator to trigger actions 

### Describe the usage

When condition is not found trigger action

### Is it a duplicate?

- [X] There is no duplicates

**Comment by ramonssarmento** [comment]
You can choose "Absent" in condition visibility, the action of the event will be trigger if the image cant be found in the respectively area

**Comment by vindaruck** [comment]
Amazing, thank you
