### ISSUE TITLE
Add STOP scenario action

### ISSUE THREAD

**Issue by vindaruck** [Nain57/Smart-AutoClicker#436]
### Describe the feature

An action that will stop current scenario 

### Describe the usage

In addition of click, pause,.. the action stop scenario stop current running scenario when condition is found like clicking on pause button 

### Is it a duplicate?

- [X] There is no duplicates

**Comment by ramonssarmento** [comment]
In scenario config there is a option called "End condition" you can set to stop the scenario after your stop event be executed once.

**Comment by vindaruck** [comment]
Great, thank you
