### ISSUE TITLE
Make the image recognition button accept smaller width.

### ISSUE THREAD

**Issue by mihaiolimpiu** [Nain57/Smart-AutoClicker#441]
### Describe the feature

While the height of the image can go quite low, the width is always quite big, even in games with really big buttons you are forced to pick a part of the background, and that quite simply affects the image recognition algorithm.

### Describe the usage

Users should be able to select exact size for the buttons they want to click, a minimum of let's say 100 pixels should make the interface still usable.

### Is it a duplicate?

- [X] There is no duplicates

**Comment by Nain57** [comment]
Are you talking about the rectangular selector to crop a condition ?
Do you know you can pinch to zoom ?

**Comment by mihaiolimpiu** [comment]
It has never occurred to me, I'll mark it as closed.
Some kind of icon would be helpful though, created a few macros, and I always tried to use the small rectangle.

**Comment by Nain57** [comment]
There is normally a pinch icon hint appearing when the screenshot is taken, but you are not the first missing it.
I need to find a way to improve it
