### ISSUE TITLE
the sequence of action events cannot be saved after adjusted

### ISSUE THREAD

**Issue by a497314013** [Nain57/Smart-AutoClicker#444]
### Version of Smart AutoClicker

3.0.0 beta4

### Device brand and model

Oppo Reno9 Pro

### Version of your Android OS

14

### Type

Smart scenario

### Describe what happened?

the sequence of action events is not effective. when I adjust the sequence of action and save the action, it can work. but once I save the scenario, it will reset to the default sequence.

### Describe what should have happened?

the sequence should also be saved after save the scenario.

**Comment by Cyber5imon** [comment]
I also have seen this issue many times. My only current workaround is to delete all action items and recreate them in order.

**Comment by WildSnail913** [comment]
I was having a problem getting a new scenario to work at all and after reading this thread and making the "override condition" events first it finally works.

Im not sure what the specific issue is but the exact same conditions wouldnt trigger when I didnt take steps to add them first.

**Comment by Nain57** [comment]
Fixed in version [3.0.1](https://github.com/Nain57/Smart-AutoClicker/releases/tag/3.0.1) and above
