### ISSUE TITLE
Running multiple simple/dumb scenarios in parallel

### ISSUE THREAD

**Issue by nucspl** [Nain57/Smart-AutoClicker#445]
### Describe the feature

I would like to be able to run two or more simple scenarios at once/in parallel. How it is set up could be done by selecting several simple scenarios to be executed before running Klick'r over an application.

### Describe the usage

I have two simple scenarios that I want to be executed at once, but can't combine the two as the actions of the other are time-sensitive with a wait timer of 15s, while the other indefinitely clicks at several areas every 1ms.

Right now, I have to use OP Auto Clicker as a stand-in for the aforementioned indefinite clicking, while Klick'r does the time-sensitive scenario. It's pretty tedious getting it all up and running every time.

### Is it a duplicate?

- [x] There is no duplicates

**Comment by Nain57** [comment]
This will lead to a lot of unexpected behaviours. Most users don't event understand how the app works given the questions a get, so I don't think adding another layer of complexity will be helpful
