### ISSUE TITLE
Feature Request - limit actions per condition

### ISSUE THREAD

**Issue by rony432** [Nain57/Smart-AutoClicker#446]
### Describe the feature

hi
wonderful app

if an event set to just One instead of All
any of found conditions will trigger all of the set actions no matter what.
 
the thing that missing is events is actions for set condition

to improve or expand this limitation, putting a setting option inside the actions (click, wait, etc) limiting it to a single condition if that condition found. (and showing name of the set condion on the action in color .. in actions tab)

by doing it this way. even if there are 100 actions only the found condition actions will be triggered rest will be waiting until their condition are found.

lets say we have 20 actions. 
conditionA has 5 actions and limiting them to conditionA, it should only trigger those 5

i hope you add this feature soon.

thanks

### Describe the usage

lets say we have 20 actions. 
conditionA has 5 actions and limiting them to conditionA, it should only trigger those 5

conditionB has 8 actions and limiting them to conditionB, it should only trigger those 8

### Is it a duplicate?

- [X] There is no duplicates

**Comment by Nain57** [comment]
Won't do: this is basivally creating a new event with extra steps
