### ISSUE TITLE
next event not start

### ISSUE THREAD

**Issue by MeroBenSU** [Nain57/Smart-AutoClicker#451]
### Version of Smart AutoClicker

2.4.2

### Device brand and model

A9

### Version of your Android OS

9

### Type

Smart scenario

### Describe what happened?

Hello all
I have a problem that I hope I can explain well
Let's say I have 4 events
All events share the same start request (photo)
Let us assume that the event A1 is clicked at the specified location
At the end of the event, I added a request to move to event A2
And so on until the end of events
But what happens to me is that it keeps pressing in the event area A1
It does not move on to the next event
I don't know if I'm doing something wrong
But for your information, I cannot add them all under one event
Because there are other events that are activated and they are a bit complicated
![image](https://github.com/user-attachments/assets/134af3e8-300b-4e48-9cac-7207d6546480)

### Describe what should have happened?

What is the correct way
To forcefully move from event A1 to event A2
Thank you

**Comment by demikian546** [comment]
Event A1: Enable A2, disable A1
Event A2: Enable A3, disable A2
Event A3: Enable A4, disable A3
Event A4: Enable A1, disable A4
