### ISSUE TITLE
Swipe on condition.

### ISSUE THREAD

**Issue by pretty-imp** [Nain57/Smart-AutoClicker#453]
### Describe the feature

I would like to have a new type of action that adds a condition to swipe.

### Describe the usage

I have a situations where I need to scroll the screen while there are no needed resources.

### Is it a duplicate?

- [X] There is no duplicates

**Comment by Nain57** [comment]
Closed: This feature can't be understood. It either contains not enough information, explainations or use cases, or does not uses the vocabulary of the app.
