### ISSUE TITLE
find event is running

### ISSUE THREAD

**Issue by talebianasal** [Nain57/Smart-AutoClicker#458]
### Describe the feature

Hello, thank you for your very good project
I have a question, how can I find out which event is running?
If you don't have this feature, how long do you think you can add this feature?
Because I want to run functions when a certain event is running

### Describe the usage

Hello, thank you for your very good project
I have a question, how can I find out which event is running?
If you don't have this feature, how long do you think you can add this feature?
Because I want to run functions when a certain event is running

### Is it a duplicate?

- [X] There is no duplicates

**Comment by Nain57** [comment]
Closed: not a feature request
