### ISSUE TITLE
Minimum size for conditions is too large

### ISSUE THREAD

**Issue by TL1882** [Nain57/Smart-AutoClicker#460]
### Describe the feature

Just let condition screen captures be a bit thinner

### Describe the usage

I'm trying to automate a game but the buttons are too small to fit perfectly in the box and some background graphics can be seen which prevents the condition from being activated

### Is it a duplicate?

- [X] There is no duplicates

**Comment by Nain57** [comment]
See https://github.com/Nain57/Smart-AutoClicker/issues/441.
