### ISSUE TITLE
The screenshot of WeChat Mini Program is blurry

### ISSUE THREAD

**Issue by breakTBB** [Nain57/Smart-AutoClicker#461]
### Version of Smart AutoClicker

2.4.2

### Device brand and model

Redmi K50

### Version of your Android OS

13

### Type

Smart scenario

### Describe what happened?

WeChat should have a detection mechanism, and the captured screenshots are blurry. It is recommended to allow the use of images directly from the album. 
One can reproduce this easily, no screenshot. 

### Describe what should have happened?

The screenshot should be clear

**Comment by hds1992012011** [comment]
I also use it on the WeChat Mini Program（小游戏 土豆英雄） and it's basically fine. On the rare occasions when recognition doesn't work, it feels like the image itself has an unclear border, causing the recognition algorithm to fail occasionally.

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

Depending on the device and the application, something called "Privacy mode" in Android can blur the application on casted screens. And that's exactly how Klick'r is doing to see what is displayed on your screen. This can sometimes be disabled in the settings of the application itself.

As there is no way for Klick'r to work without the screen casting, I will close this ticket.
