### ISSUE TITLE
[BUG?] Triggered Event is clicking another Event detected condition

### ISSUE THREAD

**Issue by KimaCuda** [Nain57/Smart-AutoClicker#467]
### Version of Smart AutoClicker

2.4.2

### Device brand and model

Samsung Galaxy S24

### Version of your Android OS

14

### Type

Smart scenario

### Describe what happened?

I don't know if this bug has already been reported, but I found it.

Event A (Full Brick Ads)
Config: Conditions All
Conditions: 2 (Condition A is mostly always exists, while Condition B is not)
Actions: Click On A when triggered
<img src="https://github.com/user-attachments/assets/9e0906be-2586-45d6-b119-a7748779ad2f" alt="Screenshot" width="300">
<img src="https://github.com/user-attachments/assets/94d29316-4990-41c3-ac37-d56e71c38640" alt="Screenshot" width="300">
<img src="https://github.com/user-attachments/assets/b37ff367-2245-47c9-a548-85ff584071ab" alt="Screenshot" width="300">
<img src="https://github.com/user-attachments/assets/20c603be-e229-422f-94b6-ff1af9348799" alt="Screenshot" width="300">

Event B (Equipment Challenge)
Config: Conditions One
Conditions: 2 (One of them is Detected)
Actions: Click (On Conditions => First Detected Condition)
<img src="https://github.com/user-attachments/assets/8f17ec97-0fe6-4019-8547-289b041b5298" alt="Screenshot" width="300">
<img src="https://github.com/user-attachments/assets/d9d9d336-ff18-492c-927c-c334a21d59a4" alt="Screenshot" width="300">
<img src="https://github.com/user-attachments/assets/f270a681-aecd-4a7f-a4b8-73bdef2f9cac" alt="Screenshot" width="300">
<img src="https://github.com/user-attachments/assets/8ded0aa5-50ad-48b7-93d2-1bc28b66bcbe" alt="Screenshot" width="300">

Somehow, when Event B (Equipment Challenge) is triggered, Instead of clicking the detected conditions of B, It's clicking the detected condition of Event A => Condition A (that mostly always exists). I don't know if this is intended, if my configuration is wrong, or if this is a bug and should be fixed.

The position of Event A is higher than event B, so it's always checked first before Event B

### Describe what should have happened?

It should've clicked the detected conditions from Event B

**Comment by Nain57** [comment]
This issue is related to: https://github.com/Nain57/Smart-AutoClicker/issues/359
ToggleEvent is bugged in 2.4.2, and is fixed in 3.0.0 that should be released by the end of the week.
