### ISSUE TITLE
Click on detected image

### ISSUE THREAD

**Issue by Balthazar1234** [Nain57/Smart-AutoClicker#47]
It would be pretty practical if the app could click directly on the center of the image section or screenshot it found.

Thanks for your work and useful app!

**Comment by bst2k** [comment]
Yea this would be awesome

**Comment by Thomas-678** [comment]
To add to this, let users define a rectangle area to search the target image in. 
I really want this app to include this feature. Without it, if a screen button can appear at multiple places, we would have to define a new click for each of them.

**Comment by Nain57** [comment]
Implemented in 1.3.0. Should be available soon on F-Droid
