### ISSUE TITLE
Accessibty issue

### ISSUE THREAD

**Issue by qadeer819** [Nain57/Smart-AutoClicker#471]
### Version of Smart AutoClicker

3.0.1

### Device brand and model

Samsung a52

### Version of your Android OS

14

### Type

Other

### Describe what happened?

Can turn on accebilty settings 

### Describe what should have happened?

Can’t turn on accessibility 
![451853d8-a72a-4ca5-a81b-917bf552d447](https://github.com/user-attachments/assets/aaadbdbe-990a-4a6f-b2e7-257ba43a3ed5)

**Comment by Nain57** [comment]
Android restriction, not related to Klick'r. Please use Google before opening up tickets: https://support.google.com/android/answer/12623953?sjid=9823337403138259061-EU#allowrestrictedsettings
