### ISSUE TITLE
[BUG] Screen Event doesn't update actions index on save

### ISSUE THREAD

**Issue by KimaCuda** [Nain57/Smart-AutoClicker#472]
### Version of Smart AutoClicker

3.0.0

### Device brand and model

Samsung Galaxy S24

### Version of your Android OS

14

### Type

Smart scenario

### Describe what happened?

When planning to add new actions to the Event, it always sorted the actions based on how latest the actions were created, not based on how I ordered them.

Example of my current action:
1. Click 1
2. Click 2
3. Click 3
4. Click 1
5. Click 2
6. Click 3

Let's say I want to set a new Action called Click 4, it should look like this:
1. Click 1
2. Click 2
3. Click 3
4. Click 4
5. Click 1
6. Click 2
7. Click 3
8. Click 4

Instead, what I get is this after sorting and saving:
1. Click 1
2. Click 2
3. Click 3
4. Click 1
5. Click 2
6. Click 3
7. Click 4
8. Click 4

### Describe what should have happened?

It shouldn't sort based on how latest the actions were created but based on index?

**Comment by KimaCuda** [comment]
The current workaround that I do is delete all the actions first and then create them again

**Comment by Nain57** [comment]
Already fixed in [3.0.1](https://github.com/Nain57/Smart-AutoClicker/releases/tag/3.0.1)
