### ISSUE TITLE
Undo the change of action

### ISSUE THREAD

**Issue by Tallavn** [Nain57/Smart-AutoClicker#473]
### Describe the feature

I always have trouble whenever I edit an action overlaying an old one and when I do that I can't go back to the old version of it. At that point I'm forced to create a new action and set it up exactly the same way as the old one if I'm lucky enough to remember the parameters.

### Describe the usage

with the people set large actions

### Is it a duplicate?

- [X] There is no duplicates

**Comment by Nain57** [comment]
Won't do: This is basically requesting version control, which is way too complicated. You can simply
