### ISSUE TITLE
Wait cannot go first

### ISSUE THREAD

**Issue by Leonelus** [Nain57/Smart-AutoClicker#474]
### Version of Smart AutoClicker

3.0.0

### Device brand and model

Motorola moto G42

### Version of your Android OS

14

### Type

Smart scenario

### Describe what happened?

I wanted to create a scenario where the first action that happens is to wait for 6 seconds then do a click. However, whenever I save the scenario, for some odd reason the order of these two actions get reversed. This only happens on the first two actions 

### Describe what should have happened?

The wait action was supposed to go first, not second.

**Comment by Nain57** [comment]
Already fixed in 3.0.1
