### ISSUE TITLE
UI is not supporting disabled animations from developer options

### ISSUE THREAD

**Issue by Nain57** [Nain57/Smart-AutoClicker#480]
### Version of Smart AutoClicker

All versions

### Device brand and model

All devices

### Version of your Android OS

All versions

### Type

Other

### Describe what happened?

Lot's of Klick'r users are disabling the animations via the Developer Options, which causes issues as the Android WindowManager is relying on animations states to resize correctly, leading to issue like mentionned in https://github.com/Nain57/Smart-AutoClicker/issues/378

In normal apps, this issue would have been ditched (see note about this Developper option below) but the "hackish" nature of the user base made the bug more apparent and thus, requires attention. 

> [!NOTE]
> **Developer Options**
>   As stated in the name, this is a feature intended for developpers allowing them to test during development, not something that should be widely used as a production feature. Furthermore, the general idea of saving battery is completely false (source: I do Android devices (not apps, DEVICES) for a living since 2012, thrust me). Finally, a lot of big app makers knows that and use their own animation systems to bypass this developer option. For your own good and the sake of all Android indie devs, please stop using it :)

### Describe what should have happened?

Ui should not rely on animation states.
I will take a look, but might be not fixable, given how the WindowManager behaves with overlay resizes

**Comment by zakius** [comment]
to be perfectly fair some phone makers put these settings as a proper user preference, obviously that still changes the same values inder the hood but general user wouldn't even realize that's designed as an advanced feature

also as long as UI are designed with blocking animations (that stop you from interacting with your device until the fancy stops playing) the need to disable them persists

and as a third excuse: for a while now Android has a bug making third party launchers glitch out but disabling animations seems to prevent that from happening so there's also that

it would be optimal if Google made it officially supported and fix their bugs but that's unlikely

**Comment by Nain57** [comment]
Should be fixed by https://github.com/Nain57/Smart-AutoClicker/commit/96dbb202ed4cc5b8fae259d9a7f8b8c0f4b832ec

**Comment by Nain57** [comment]
Closed, release will be available once built (~30mins) here: https://github.com/Nain57/Smart-AutoClicker/releases/tag/3.0.4
If you can still reproduce the issue, feel free to open it again
