### ISSUE TITLE
Scenarios are not working

### ISSUE THREAD

**Issue by empjustine** [Nain57/Smart-AutoClicker#5]
I have 2 distinct click scenarios with distinct conditions and targets. However, no matter what click scenario I pick on the main activity, it only checks for the conditions and use the targets of the first click scenario.

How I can collect useful logs/evidence to pin this down?

**Comment by Nain57** [comment]
If you know how adb works, you provide the logcat with the command 'adb logcat'

If not, a video of the this bug might be useful

**Comment by NguyenDuck** [comment]
I think should add a setting line to output log with 1 file

**Comment by empjustine** [comment]
While attempting to generate a ADB log smaller that 100MB to submit to you, I noticed some issues regarding Accessibility service permissions being lost and not correctly reassigned.

It looks like on my specific device, I need to enable, disable and enable again Accessibility service, or the app doesn't actually get the permission to interact with the device.

I'm closing the ticket now as after said enable-disable-enable steps, the app works as intended.
