### ISSUE TITLE
Issue with event enabling/disabling cycle (toggle)

### ISSUE THREAD

**Issue by hsantanna** [Nain57/Smart-AutoClicker#501]
### Version of Smart AutoClicker

3.0.3

### Device brand and model

crdroid 10.8 (build 14.09) on Mi9 (Cepheus)

### Version of your Android OS

14

### Type

Smart scenario

### Describe what happened?

Description: I am encountering an issue with the behavior of three events in the program. The expected logic and the actual behavior are as follows:

Event 1: Starts enabled.

Event 2: Starts disabled.

Event 3: Remains always enabled.

Issue encountered: After Event 1 is triggered, it correctly disables itself and enables Event 2, but from that point onward, only Event 3 continues to be triggered. Neither Event 1 nor Event 2 are triggered again, breaking the expected cycle between them.

Steps to reproduce:

1. Start the program with the three events: Event 1 enabled, Event 2 disabled, and Event 3 always enabled.

2. Trigger Event 1.

3. Try to trigger Event 2 (which should now be enabled).

4. Notice that only Event 3 continues to be triggered, while Events 1 and 2 no longer function.

### Describe what should have happened?

The expected logic is:

When Event 1 is triggered, it disables itself and enables Event 2.

When Event 2 is triggered, it disables itself and re-enables Event 1.

Event 3 is unaffected by these changes and remains always enabled.

Expected behavior: After Event 1 is triggered, Event 2 should be enabled and Event 1 disabled. When Event 2 is triggered, it should disable itself and re-enable Event 1, creating a cycle between the two events.

Event 2 should be triggered after Event 1, and the cycle between the two events should continue normally.

Observed behavior: Only Event 3 remains functional, and neither Event 1 nor Event 2 are triggered again.

**Comment by hsantanna** [comment]
Test scenario 
[SmartAutoClicker-Backup-event_toggling_bug.zip](https://github.com/user-attachments/files/17036188/SmartAutoClicker-Backup-event_toggling_bug.zip)

**Comment by Nain57** [comment]
Hi and thank you for your feedback.
Bug have been reproduced in test environment. It will be fixed in the next version.

**Comment by Nain57** [comment]
Fixed by: https://github.com/Nain57/Smart-AutoClicker/commit/8f18b58f5d51c3e583b0d8a816e4c52d4d6282d7

**Comment by hsantanna** [comment]
I can confirm that it's fixed.

Thank you very much for your great app, @Nain57
