### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by Ryoschin** [Nain57/Smart-AutoClicker#505]
### Describe the feature

Let us duplicate certain gestures, as well as Scenarios! Seriously, a 100+ length scenario takes time I am not willing to put in order to be duplicated. (also, even if this is somehow possible using the save option, it is not working as of now, as described in another issue)

### Describe the usage

People can go crazy copying their own already-made gestures and scenarios, we need a way of staying sane!

### Is it a duplicate?

- [X] There is no duplicates

**Comment by Nain57** [comment]
Closed because I don't like the tone.
App is available for free and developed on my free time, I don't know who you think you are.

Furthermore, I can't even understand the request you are making.

Closed + Banned
