### ISSUE TITLE
Clicking buttons around the image recognized on the screen?

### ISSUE THREAD

**Issue by justuseown** [Nain57/Smart-AutoClicker#515]
### Describe the feature

After image recognition, click the buttons around the recognized image.In addition, can the image recognition range be increased? Currently, the minimum is only 80%, but in practice, 60% often already encompasses the dynamic content needed.

### Describe the usage

Often, images are dynamic and hard to recognize, but the fixed text near the images is easier to identify. However, the images serve as interactive buttons, while the text does not have any interactive functionality. Therefore, can we add a new feature: "recognize the image, then click the button within a certain number of pixels around the image (ideally, add a GUI to intuitively select where nearby to click)?"In addition, can the image recognition range be increased? Currently, the minimum is only 80%, but in practice, 60% often already encompasses the dynamic content needed.

### Is it a duplicate?

- [X] There is no duplicates

**Comment by hsantanna** [comment]
Duplicate for #484
