### ISSUE TITLE
[FR] Reorder actions

### ISSUE THREAD

**Issue by aviladev** [Nain57/Smart-AutoClicker#52]
It would be nice to have this feature since sometimes I delete an action by mistake and then have to delete all actions and recreate all of them. Also sometimes I forget to create a wait action between two click actions, and then I have to delete the last click to create it.

**Comment by Nain57** [comment]
Hi !

Action reorder and action copy features are already developed and will be included in the next release centered which is centered on QoL.

But thanks for your contribution !

**Comment by Nain57** [comment]
Feature implemented on last version: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.2.0
It should be available on F-Droid soon.
