### ISSUE TITLE
New Volume down dialogue can't be dimissed in landscape mode

### ISSUE THREAD

**Issue by shmaungms** [Nain57/Smart-AutoClicker#525]
### Version of Smart AutoClicker

3.0.5

### Apk

F-Droid

### Device brand and model

Oneplus Nord 2 5G

### Version of your Android OS

13

### Type

Smart scenario

### Describe what happened?

![Screenshot_2024-10-16-16-11-27-92_eac419a32b159bf0f4e61ede32fbd888](https://github.com/user-attachments/assets/9c86d024-bacc-4201-98a7-ce99fea4ec5c)

It took me a few minutes to work this out as I could click "don't show this again" but it just kept coming up again and again when I dismissed it by clicking outside the box. It was only after putting my phone in portrait I could see the understood button. Swiping up and down (which isn't intuitive) didn't work either to show the "understood" button when in landscape.

### Describe what should have happened?

I should be able to see the understood button when in landscape.

**Comment by Nain57** [comment]
Fixed by https://github.com/Nain57/Smart-AutoClicker/commit/cda126799f4464ae1199bdd8619a218e04039045

**Comment by Nain57** [comment]
Fix available in 3.0.6: https://github.com/Nain57/Smart-AutoClicker/releases/tag/3.0.6
If you still encounter this issue, feel free to reopen tis ticket.
