### ISSUE TITLE
App content hidden from screen share

### ISSUE THREAD

**Issue by Beepboop86** [Nain57/Smart-AutoClicker#527]
### Version of Smart AutoClicker

3.0.5

### Apk

PlayStore

### Device brand and model

Google Pixel Tablet

### Version of your Android OS

15

### Type

Other

### Describe what happened?

I recently updated to Android 15. When I try to use the smart clicker on an app, it doesn't do anything. I noticed that when I open the app I have been using the clicker on, there's a pop up on the bottom of the screen that says "App content hidden from screen share for security"

### Describe what should have happened?

The smart clicker should smart click.

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

The application you are trying to use Klick'r on is using the new Android 15 privacy settings, hidding it's content to all media projection. There is nothing i can do about that.

Closed because can't be fixed.
