### ISSUE TITLE
DUMB/SIMPLE SCENARIO EDTINGS ACTION ISSUE

### ISSUE THREAD

**Issue by twg88** [Nain57/Smart-AutoClicker#528]
### Version of Smart AutoClicker

3.0.6

### Apk

Github

### Device brand and model

SAMSUNG GALAXY S24 SM-921B/DS

### Version of your Android OS

14

### Type

Dumb scenario

### Describe what happened?

Editing 2nd/3rd action AT SIMPLE/DUMB SCENARIO results in 1st action "OVERTAKING/OVERRIDING" the 2nd, 3rd action.

Here's a video of said issue.

https://github.com/user-attachments/assets/0c2f96cc-f35e-49b3-9912-f5f102c2d46a

### Describe what should have happened?

Editing 2nd/3rd action should NOT be edited/affected by 1st action.

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

The bottom left and right button are for moving the action in the list, you need to swipe left/right to display the previous/next action. As you are pressing right, the first action is becoming the second one. (I hope i have been clear with my explaination, if not, give different names to your actions and you will understand)

This is not a bug, more a misunderstanding of the reorder buttons (those are the regular material icons for left/right move). I might add a tutorial screen at first start to explain it better in a future version, as you are not the first one making this mistake.

**Comment by twg88** [comment]
> Hi and thank you for your feedback.
> 
> The bottom left and right button are for moving the action in the list, you need to swipe left/right to display the previous/next action. As you are pressing right, the first action is becoming the second one. (I hope i have been clear with my explaination, if not, give different names to your actions and you will understand)
> 
> This is not a bug, more a misunderstanding of the reorder buttons (those are the regular material icons for left/right move). I might add a tutorial screen at first start to explain it better in a future version, as you are not the first one making this mistake.

Yep, tutorial or a manual would be great, darn, wouldn't think of swiping that. #facepalm

**Comment by potchy** [comment]
lol same I spent like an hour with the same issue
