### ISSUE TITLE
Scenario Detection Quality speed

### ISSUE THREAD

**Issue by shakibmolla** [Nain57/Smart-AutoClicker#530]
### Describe the feature

![IMG_20241022_230119](https://github.com/user-attachments/assets/785d20c6-6958-4991-891d-3cb7ff82e50e)
It's possible to add Scenario Detection Quality speed 0 or 1 you can add custom Detection Quality speed and precision.

### Describe the usage

More accuracy detect and more fast work.
You set Detection quality speed 400. So this not detect properly. I recommend you add custom speed option feature.

### Is it a duplicate?

- [x] There is no duplicates

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

Detection quality is not a magic value allowing to increase speed without any cost, it is the actual width the screen frame will be scale to in order increase the processing time. Going below 400 will start to create a pixel mush where nothing can be detected at all.

Accuracy also is determined by the Detection quality. If the quality is higher, the screen frames will be less scaled down and the detection more accurate, but it will take more time.

Performances also depends on your condition: 
 * Try to keep your condition as small as possible, but without sacrificing details (avoid single color conditions). 
 * Try to keep the detection area as small as possible
 * Avoid capturing area with transparency. If the image is displayed over another background, the color will ne be the same and the detection will be less accurate

Keep also in mind that detection speed is tied up to your phone performances. If you have a low end phone (or a phone like Xiaomi that cheats on their benchmark to be higher than other phones but actually runs like a potato phone), you will always get poor performances.

**Comment by shakibmolla** [comment]
thank u so much
