### ISSUE TITLE
Hidden UI prevents touches

### ISSUE THREAD

**Issue by timkrief** [Nain57/Smart-AutoClicker#557]
### Version of Smart AutoClicker

3.0.6

### Apk

F-Droid

### Device brand and model

S21 Ultra

### Version of your Android OS

14

### Type

Smart scenario

### Describe what happened?

When hidden through the notification, it's impossible to touch or swipe around where the UI was before hiding.

There is a tedious workaround that I found, it's to disable the overlay permission after hiding. But you would have to do that each time you want to hide, and re-enable it each time you need to start a new event.

### Describe what should have happened?

Normal use of the touch screen

**Comment by Nain57** [comment]
Fixed by: https://github.com/Nain57/Smart-AutoClicker/commit/4f8f167e0e34a827057233e8703cbd7a0eb87bf8
Will be available in Klick'r 3.1.0

If you still encounter this issue, feel free to reopen this ticket.
