### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by potchy** [Nain57/Smart-AutoClicker#558]
Hello! Have you considered adding a donation button somewhere? This app is amazing and saves me a lot of time. It's crazy that it's free.

**Comment by Nain57** [comment]
Hi and thank you for your support.
The PlayStore version is my way to be retributed (taxes in france are complicated for donations). This is the same app but with advertisement, removable via a one time purchase of 5$ (prices might depends on your country).

**Comment by potchy** [comment]
Thanks! I just bought it on the Play Store. Have a nice day.
