### ISSUE TITLE
backup error in version 3.1.0

### ISSUE THREAD

**Issue by talebianasal** [Nain57/Smart-AutoClicker#561]
### Version of Smart AutoClicker

3.1.0

### Apk

PlayStore

### Device brand and model

any

### Version of your Android OS

any

### Type

Smart scenario

### Describe what happened?

I can't use the backup I took from the old version in version 3.1.0.

### Describe what should have happened?

We should be able to import the backups we took from previous versions into the new version without any problems.

**Comment by talebianasal** [comment]
logcat :

Can't find keepDetecting
Can't find clickOnConditionId

**Comment by talebianasal** [comment]
[a.zip](https://github.com/user-attachments/files/18049304/a.zip)

You will see that this file is imported without any problems in the old version, but in the new version it encounters an error.

**Comment by Nain57** [comment]
Should be fixed by: https://github.com/Nain57/Smart-AutoClicker/commit/6700b1f022d90e0da72dcf0048e3d4131ab22a18

**Comment by Nain57** [comment]
Fix available in 3.1.1: https://github.com/Nain57/Smart-AutoClicker/releases/tag/3.1.1 (available as soon as the build finishes, or within a few days on F-Droid/PlayStore)

If you are still encountering this issue, feel free to reopn this ticket.

**Comment by talebianasal** [comment]
Fixed
Thank you
