### ISSUE TITLE
Error with Smart Scenario

### ISSUE THREAD

**Issue by Sorax117** [Nain57/Smart-AutoClicker#566]
### Version of Smart AutoClicker

3.1.0

### Apk

Github

### Device brand and model

TECNO SPARK go 2023

### Version of your Android OS

12

### Type

Smart scenario

### Describe what happened?

I downloaded the application from github, without making any changes, I am using Android Studio 2024.1.1 on Ubuntu. When executing a smart scenario, this window pops up. What can I do?

![Image](https://github.com/user-attachments/assets/3bf900ae-413c-43f4-8898-97d2601bd099)

### Describe what should have happened?

should have run normally

**Comment by Nain57** [comment]
As stated in the bug report form, I do not provide support on custom installations of Klick'r.
If you reproduce the issue with an proper installation of an apk generated by me, feel free to reopen the ticket
