### ISSUE TITLE
I need a 15-minute-long swipe, but the input field is limited to 9999 ms.

### ISSUE THREAD

**Issue by GammelSami** [Nain57/Smart-AutoClicker#572]
### Describe the feature

Let the user put in more digits into the Swipe duration field.

### Describe the usage

So I wanna use an app that has a "push to talk" feature but hands-free. They don't allow you to lock it while talking so I'd use this Autoclicker App and just stop the script every time I finished talking.

### Is it a duplicate?

- [X] There is no duplicates

**Comment by Nain57** [comment]
Hi and thank you for your feedback.

That's impossible due to Android limitations on injected gesture. The maximum value in the app is already the maximum value supported by Android.

**Comment by GammelSami** [comment]
It's possible when I use ADB but my phone starts dropping frames when I do it multiple times.

A workaround could be a negative repeat delay.
