### ISSUE TITLE
[FR] Toggle to easily enable/disable events

### ISSUE THREAD

**Issue by vdurante** [Nain57/Smart-AutoClicker#58]
Hey, great job and thanks for implementing last features I asked for.

Use case: sometimes I want to disable or enable a few events throughout the day, to alter the flow a little bit

FR: would be super cool if there was a toggle to easily enable/disable events on the list

TIA

**Comment by Nain57** [comment]
Implemented and will be part of the next version.

**Comment by Nain57** [comment]
Release 2.0.0 containing a fix for this is now available on Github and should be available soon on F-Droid.
