### ISSUE TITLE
[BUG] Reordering disappears with events

### ISSUE THREAD

**Issue by vdurante** [Nain57/Smart-AutoClicker#59]
When I am reordering, it is common that an event simply disappears from the list, gone forever. Or the reordering scramble things around

**Comment by Nain57** [comment]
Hi !
I have tried to reproduce this issue without success on several devices. I will need more information in order to find it.

Can you provide your Phone brand, Android version and how many event you have in your scenario ? Any other information that can help me fix it is welcomed !

**Comment by vdurante** [comment]
@Nain57 I haven't had this issue in a while. If I ever face it again I will record a video and reopen the issue.

**Comment by Nain57** [comment]
Ok, thanks for your feedback !
