### ISSUE TITLE
Constant creashes happening on Samsung S10 Lite when creating/editing event

### ISSUE THREAD

**Issue by vdurante** [Nain57/Smart-AutoClicker#60]
I tried to find some log info but wasn't able to do so. I could help you out to fix it.

**Comment by Nain57** [comment]
[Smart-AutoClicker 1.2.2](https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.2.2) is now available. It should fix this issue.
The update should be available soon on F-Droid.
