### ISSUE TITLE
[BUG] When setting click time to zero, app crashes

### ISSUE THREAD

**Issue by WesleyMarz** [Nain57/Smart-AutoClicker#68]
Not that we'd ever set it to 0ms, just noticed it crashes. 1ms works fine.

**Comment by T5ive** [comment]
Naturally, there is no other CPU in the world that can support clicker 0ms performance, my friend.

**Comment by Nain57** [comment]
Thx for the feedback.
0ms duration should be not be possible to input. This will be fixed in the next version.

**Comment by Nain57** [comment]
[Smart-AutoClicker 1.2.3](https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.2.3) is now available. It should fix this issue.
The update should be available soon on F-Droid.
