### ISSUE TITLE
App keeps crashing after defining a condition

### ISSUE THREAD

**Issue by Metazolid** [Nain57/Smart-AutoClicker#7]
More often than not, when/after defining a condition the app just crashes. Using the app C.A.T.S. in this case. Most of the time, the app softlocks itself as detailed in my Accessibility Service issue.
![Screenshot_20210606-114924](https://user-images.githubusercontent.com/17498384/120920108-80fb3f00-c6bd-11eb-867e-ea0b484e8a3e.jpg)

**Comment by Nain57** [comment]
As I can see from your screenshot, you are using it in horizontal orientation. 
There is currently a stability issue due to the orientation change as described here https://github.com/Nain57/Smart-AutoClicker/issues/4

I am currently working on it and should be fixed in the next version.

**Comment by Metazolid** [comment]
Awesome! Let me know if you need any info/screenshots :)

**Comment by Nain57** [comment]
This should be fixed with version 1.0-RC2 : https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.0-RC2
It should be soon released on F-Droid, but the .apk is already available with the release note.

I will close this ticket upon your confirmation.

**Comment by Metazolid** [comment]
Can confirm, it's working now!
