### ISSUE TITLE
Rotate not working. Overlay only on left half

### ISSUE THREAD

**Issue by Skavis** [Nain57/Smart-AutoClicker#70]
After turning everything on for the app and the overlay is on screen. When launching the game the overlay is only registering on the left half of the screen. As if the phone is in vertical mode when it's actually horizontal. This only started happening after the update to android 12. It was happening periodically, but now seems to be just about everytime.  To be clear.  Smartclicker launched and rotates with the screen but if you were to click and drag smartclicker overlay, it gets stuck half way and you can't move it to the right side of the screen. When running a scenario it only is seeing the left side of the horizontal view.

**Comment by Skavis** [comment]
Here is a link to screen capture to show you what I mean

**Comment by Nain57** [comment]
Hi !
There is indeed an issue with the screen rotation on Android 12. I'm currently investigating and I will fix it for the next version.
Thanks for your feedback !

**Comment by Nain57** [comment]
Fix found and merged with the project ! It will be part of the next Smart Autoclicker version.

**Comment by Nain57** [comment]
[Smart-AutoClicker 1.2.3](https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.2.3) is now available. It should fix this issue.
The update should be available soon on F-Droid.

**Comment by Skavis** [comment]
You are incredible!
