### ISSUE TITLE
Excute swipes based on keypresses from a physicalkeyboard or controller

### ISSUE THREAD

**Issue by deoxal** [Nain57/Smart-AutoClicker#71]
I wasn't sure if it was possible right now but since this app lets you simulate input I know it is now. I haven't seen this done elsewhere and I was curious about your thoughts.

**Comment by Nain57** [comment]
I'm not sure to understand your request. You want to trigger a swipe upon press from a controller button ?

**Comment by deoxal** [comment]
Yes controller buttons but more importantly the thumbsticks.

If I push the right thumbstick past the deadzone then swipe from the center point I selected to the same direction I pushed the thumbstick and hold there until I release the thumbstick.

The reason for this is some games don't have controller support even though they would benefit a lot from them.

**Comment by Nain57** [comment]
Unfortunately, this not the goal of this application. This feature won't be added.
