### ISSUE TITLE
[FEATURE REQUEST] Click then Stop that scenario

### ISSUE THREAD

**Issue by 19ChuAnh13** [Nain57/Smart-AutoClicker#73]
Ok this will happen like this. First check for the A condition. If it was true, the associated touch action will be executed and continue with condition B UNTIL IT IS MET, NOT CHECK CONDITION A AGAIN , and so on with the condition C. If the A is fail, check again until it is found then do next step. This will avoid that 2 conditions are found on the screen at the same time. Thanks for reading

**Comment by Nain57** [comment]
Event state control will be part of the next version.

**Comment by Nain57** [comment]
Release 2.0.0 containing a fix for this is now available on Github and should be available soon on F-Droid.
