### ISSUE TITLE
Pressing Capture Button Doesn't Capture Screen Image

### ISSUE THREAD

**Issue by coridn** [Nain57/Smart-AutoClicker#74]
This is happening pretty consistently and I'm not sure why.

I've set this up on 2 actual phones and 2 emulators, but I'm having this issue constantly with one of the actual phones.

If I go to set up an image to look for, I hit the square to capture...and it just sits there.  It never captures an image.  I'm forced to lock my phone, and hit the notification and reselect the scenario to get out of the mode.

**Comment by Nain57** [comment]
This happen when the application have crashed. (Android doesn't seem to detect it and keep the overlay displayed, with no interaction possible.)

I have already fixed a similar bug, what version of Smart AutoClicker are you using ? (last version is 1.2.2)
If you are already using the last version, can you provide me more information about your phone and the bug ?
* Phone brand/model
* Android version

If possible: 
* A screenshot
* The logcat 

Thanks !

**Comment by Nain57** [comment]
Unable to reproduce.
No new informations -> Closed
