### ISSUE TITLE
[Bug] The Next Click List Doesn't seem to work

### ISSUE THREAD

**Issue by tomose-shunsaku** [Nain57/Smart-AutoClicker#8]
I Have Added a new Click list (1 Click) Below the Swipe one.

Only the swipe one works, and the app ignores the click one.

The Reorder feature is okay, but it always ignores the second one.

**Comment by NguyenDuck** [comment]
It seems to work not in an order, but only by condition.
Whenever condition is true then it will execute click

**Comment by Nain57** [comment]
You are creating two different click scenarios ?
Only one scenario at a time is ran, if you create two clicks in two different scenarios, they will never be interpreted together.

Within a same scenario, if your click list contains several clicks, the behaviour will be the following:

* The conditions of the first click will be checked
* If the condition is found on the screen, the associated touch action will be executed and then nothing will happen during the define "Delay after". Finally, the execution will start back to the beginning.
* If the condition is not found, the second click in the list will be checked.
