### ISSUE TITLE
Feature Request: import/export scenarios

### ISSUE THREAD

**Issue by sudomain** [Nain57/Smart-AutoClicker#81]
Hello,

For portability between devices it'd be nice to be able to import/export certain scenarios to different files.

Some things to consider:
1. To allow for exporting only some scenarios (not all)? For example Key Mapper allows long pressing on a keymap which causes all maps to appear in a check box list. It also shows `select all` and `backup` (export) buttons.
2. To allow arbitrary naming of the exported file?
3. A compressed file format? .zip?

**Comment by TillF** [comment]
+1 for exporting scenarios. This would be extremely useful, especially for complex stuff generated.

**Comment by TWT233** [comment]
+1, from another side, it's useful to share game scenarios along with the app
and an importable config file makes it easier to get start with this awesome app

**Comment by Nain57** [comment]
Feature implemented in 1.5.0
