### ISSUE TITLE
Feature request: event action to send an user supplied intent

### ISSUE THREAD

**Issue by sudomain** [Nain57/Smart-AutoClicker#82]
Not sure how I missed this. #44 is playing a scenario when an intent is received. This feature request is the opposite: an event action to send an user supplied intent. This would be a key feature in integration with other automation apps.

**Comment by Nain57** [comment]
The new version of Smart AutoClicker now povides Intent actions for your event: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.4.0

It should be available soon on F-Droid
