### ISSUE TITLE
After upgrade to Android 12 some of my conditions stopped working

### ISSUE THREAD

**Issue by zakius** [Nain57/Smart-AutoClicker#84]
I can't figure out why exactly and probably won't be able to assist you too much in debugging this, this might as well be some positioning issue (but in that case shouldn't all conditions stop working? or the default 1% tolerance is enough to keep some of them working?) But I thought it's worth noting it happened

**Comment by Nain57** [comment]
I have run severals tests but i can't really reproduce the issue.
Maybe your phone/app have changed something in the UI when running on Android 12. Something like a bigger status/navigation bar can change the way applications are displayed and this will cause problem to your conditions.

**Comment by zakius** [comment]
there's nothing I'd notice and for some reason not all of conditions got affected, may be some weird interaction between android versions and Unity for example causing some elements to be placed slightly differently, but without going back and forth with versions I won't be able to pinpoint it
but as you said it may as well be status bar or navbar size and some elements being anchored to the top and others to the bottom caused only some conditions to break, thank you for looking into this

**Comment by Efreak** [comment]
Any of the following would help to debug this and similar issues in the future (app changes button order, user toggles fullscreen for app, etc):

- show transparent condition on screen, with a transparent outline
- when viewing conditions, change the background color depending on whether it is currently being met (requires ability to move the window to check conditions in the middle of the screen)
- show names of currently met conditions in an overlay (possibly also show actions being performed)
- when *editing* an action, show the action on screen like is done while creating it, to allow a preview of what will happen. IE if I tap on `Click  941, 973` to edit the action, start with the circle on 941,973. This allows checking to make sure the action is actually in the correct place.
