### ISSUE TITLE
Feature request: Tasker integration

### ISSUE THREAD

**Issue by xTeooo** [Nain57/Smart-AutoClicker#85]
Hello! 
at the beginning I want to say that u did amazing work with this project. From weeks was searching simple app to compare objects on screen n execute actions.
I see we have [44](https://github.com/Nain57/Smart-AutoClicker/issues/44) here and here [82](https://github.com/Nain57/Smart-AutoClicker/issues/82) INTENT request.
Do you plan add Tasker integration as plugin ?

best wishes!

**Comment by Nain57** [comment]
Intent actions are already scheduled for a future version.
I don't use tasker, what do you want to support ?

**Comment by xTeooo** [comment]
With time I decided to hit Kotlin. 
Since ur source code is available, adding my enhancement all by myself gonna be nice startup project for me.
I'll push anything if I'm gonna be sure that everything works.

(You and ur project are with few other things managed to change my mind and start learning new things, thanks @Nain57 😌)

Best wishes
Teooo
