### ISSUE TITLE
[FR] Add D-Pad for controlling the clicks more precisely

### ISSUE THREAD

**Issue by tomose-shunsaku** [Nain57/Smart-AutoClicker#9]
When i tried to move the clicks area, i cant get the right position because if i touch the clicks area just a bit, it moves. Can you add D-Pad to be able to control on picking the clicks / swipes area as precisely as possible?

**Comment by Metazolid** [comment]
I feel like being able to edit the x y coordinates would be easier to implement to get to the same solution.

**Comment by skilbhumen** [comment]
Right now we only have trigger conditions which activates the clicking
could we also have one which stops the clicking when it sees the condition
image, because all conditions must be true is not always usable

**Comment by Nain57** [comment]
Just to be sure I understand your issue: you are trying to capture a small image condition and the selector isn't precise enough ?

If that's the case I will try to find a way to optimize it. This will be in my list of enhancement.

For the other issue just above, this seems unrelated to his thread, you might want to create another one for easier tracking.

**Comment by vdurante** [comment]
I am also having a hard time on this one. Resizing is hard when you are in a small square

**Comment by Nain57** [comment]
In the lastest release, I have reworked completely the click condition capture user experience thanks to your feedback.

The capture is now splitted in two steps:
* First, you have to take a full screenshot of the screen
* Then, you can move the square selector as the previous version, but you can now move/zoom on the screenshot.

This should make it easier to create small or quick images for the click conditions.

Let me know if like or not this solution.
