### ISSUE TITLE
Live preview/logging running scenario for troubleshooting

### ISSUE THREAD

**Issue by Metazolid** [Nain57/Smart-AutoClicker#90]
At some point a scenario becomes rather complicated and a condition from one event may overlap with one from another. I guess putting events in a specific order should take care of that issue but quite often I feel like that's not the case.
It would be pretty helpful to see which event is currently doing its thing on the screen and considering that they can pass by within a couple milliseconds, it would make sense to have them in a log file as well.

**Comment by Nain57** [comment]
A first approach to the scenario debugging have been made on 1.3.0.
Long press the play button when starting the detection ;)
