### ISSUE TITLE
Show where a click/swipe is located on screen when editing.

### ISSUE THREAD

**Issue by Metazolid** [Nain57/Smart-AutoClicker#91]
It would be nice to have the option in the click position tab to see where it actually taps on the screen. The coordinates can help with that but as someone who doesn't know a whole lot (and frequently mixes up x and y coordinates), they're only narrowing it down to a vague guessing game.

**Comment by Oxika95** [comment]
Came here to also request this feature. I dont see where it is possible to enable.
