### ISSUE TITLE
New update doesn't work on Bluestacks 5 emulator

### ISSUE THREAD

**Issue by pseudomasq** [Nain57/Smart-AutoClicker#93]
![Screenshot_2022 02 06_03 27 19 806](https://user-images.githubusercontent.com/76476344/152656197-f5b9de6b-8602-4e81-b85d-ed8289c5b3a1.jpg)
Updated from 1.2.2 to 1.2.4 and my scenarios stopped working and the screen capture looks like this.

**Comment by Nain57** [comment]
I didn't even know the application was working on Bluestacks ^^.
How did you installed it ? When I try to install my debug apk, it says it is not supported without any information. Which apk did you use ?

**Comment by xTeooo** [comment]
Tested it on bit older BS version, 4.270. Can confirm that not working here too.

**Comment by Nain57** [comment]
This issue should be fixed in the new version: https://github.com/Nain57/Smart-AutoClicker/releases/tag/1.4.0
It should be available soon on F-Droid
