### ISSUE TITLE
Bug: Wait action starts prematurely before swipe actions finish

### ISSUE THREAD

**Issue by AciesE** [Nain57/Smart-AutoClicker#95]
I guess this is an issue only noticeable when using long swipes.

I set a 'swipe' action from point1 to point2 that last 2000ms (2s), then 'wait' for 2s. When executing, I noticed that the 'wait' action starts from point1 of the 'swipe' and does not wait for point2 to be reached before going to 'wait'. So the swipe lasts for 2 seconds, and the wait is skipped (or already done since it is also 2 seconds) then the next action starts.

Of course the workaround for now is to put a 'wait' for 4s to get an actual 2s wait after the swipe, but this kind of issue may cause timing issues for longer action sequences with many short swipes and waits.

**Comment by AciesE** [comment]
Hi, i just did a little more testing. If the actions are
1) 2 second swipe from point1 to point2
2) 1 second wait
3) 2 second swipe from point1 to point2
When executing, Action (1) starts for 1 second, then Action (3) starts and swipes for 2 seconds.

Even worse, the phone HANGS if the actions are
1) 2 second swipe
2) NO wait
3) 2 second swipe
When executing, it looks like the phone is overwhelmed. I set 'showing touches' on the screen, but I do not see any slow swipe touches.
I cannot pause the macro and I struggle to get control of the phone as none of my touches are registered, because the phone is overwhelmed with the macro trying to start infinite 2-second swipes 0 seconds apart from each other. 
So Action(1) starts for 0 seconds, then Action(3) starts for 0seconds, then Action(1) again since the macro loops etc etc (i think this is happening, more on this below).




I looked at your files and may infer the cause. I think the reason why this happens is how the two threads are implemented. 

In ActionExecutor.kt, there is the workerthread and the mainthread. The list of clicks and swipes are read by the workerthread, then the actual touch gestures are sent to be performed in the mainthread (through executeClick, executeSwipe). The problem is that the list of actions read by the workerthread are done with no pause inbetween, it sends the action to the mainthread, then moves on to the next index immediately without waiting for the gesture to be done, since its done in another thread.

I think there is a solution to this, and it is in how you implemented the 'wait' action, which is not really an action but instead I see that the function just starts the next action after a delay using workerThreadHandler.postDelayed.

I feel that you can use postDelayed not only in 'pause' in line77, but in line73 and 74 too.

What the workerthread should be:
1) Index0 click1 action, _sends to mainthread_
2) postDelay index1 using click1.duration (5ms)
3) Index1 swipe1 action, _sends to mainthread_
4) postDelay index2 using swipe1.duration (500ms)
5) Index2 wait action, _nothing to send_
6) postDelay index3 using wait.duration
7) etc

mainthread:
1) clicks at click1 location
2) swipes at swipe1 location
3) waits
_all in sync with the workerthread with the correct click/swipe timings_


This is my suggestion, after looking at your code and doing a short playtest for you
I may be wrong though! I don't really know kt or java. Let me know what you think 😄!

**Comment by Nain57** [comment]
Hi ! Thanks for all those this information !
There is indeed an issue, the worker thread doesn't wait for action completion, which causes this issue. It will be fixed in the next version.

For now, I recommend using a pause action to avoid this issue.

**Comment by Nain57** [comment]
Fixed in 1.3.0. Should be available soon on F-Droid
