### ISSUE TITLE
react to change of pixels in detection area

### ISSUE THREAD

**Issue by BenjaminWegener** [Nain57/Smart-AutoClicker#96]
thanks for this excellent software!

i would like to have the option to not only react to all conditions or one condition, but to react, if the detection area changes.

thank you!

**Comment by BenjaminWegener** [comment]
https://github.com/Nain57/Smart-AutoClicker/pull/97

**Comment by Nain57** [comment]
Thanks for the contribution. 
I don't have much time to look at the pull request nor the feature added yet, but i will definitely look at it first once i've got time.

**Comment by rizaemet** [comment]
I compiled and tried it. It works exactly as expected. Thank you @BenjaminWegener for the contribution and @Nain57 for software.

**Comment by BenjaminWegener** [comment]
renamed fork, but its the same as https://github.com/Nain57/Smart-AutoClicker/pull/97 , new one is ger: https://github.com/Nain57/Smart-AutoClicker/pull/99

**Comment by Nain57** [comment]
Feature included in 1.3.0.
Should be available soon on F-Droid
