### ISSUE TITLE
Play all scenarios list?

### ISSUE THREAD

**Issue by LeeHoan** [Nain57/Smart-AutoClicker#98]
I play an online game and i really like this app. But I do individual scenarios for each day activity. How i run all scenario list for the whole day/ or put several scenarios together and run them all?
If I make a new scenario and copy each event it's really a hard work because I have 30 scenerios and each scenario has 10 events.

**Comment by Nain57** [comment]
I have planned to add more feature to the scenario management in the next versions, but it's not first in the list.
Adding an option to combine scenario together can also be a good addition, I will add it to my list.

**Comment by LeeHoan** [comment]
Thank you very much. Hope you get attention to my comments. There are many events with the same condition so I can't put them all in one scenario. On the other hand, if you run the scenario list and clear the memory of the finished scenario (only load the running scenario) it will save the phone power.

**Comment by Efreak** [comment]
Suggestion: add an action to process another scenario (and *optionally* return). This would allow a master scenario that doesn't define individual actions to be taken.
